### ISSUE TITLE
Throw error when I execute "npm start" command and access the page？

### ISSUE THREAD

**Issue by handoing** [facebook/react-vr#105]
when I execute "npm start" command and access the page, Chrome console “Internal Server Error” in index.vr.bundle:1

`GET http://localhost:8081/Samples/LayoutSample/index.vr.bundle?platform=vr&dev=true 500 (Internal Server Error)`

`blob:http://localhost:8081/0ada80be-cd9f-42cc-91e8-0b3e3e9bd960:18 DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:8081/Samples/LayoutSample/index.vr.bundle?platform=vr&dev=true' failed to load.
    at onmessage (blob:http://localhost:8081/0ada80be-cd9f-42cc-91e8-0b3e3e9bd960:15:7)`

`GET http://localhost:8081/Samples/LayoutSample/index.vr.bundle?platform=vr&dev=true 500 (Internal Server Error)`

Unable to resolve module `fbjs/lib/keyMirror` from `/Applications/learn/preview/node_modules/react-vr/Libraries/VrButton/VrButton.js`: Module does not exist in the module map or in these directories:
  /Applications/learn/preview/node_modules/fbjs/lib

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.`

* React VR version: 0.3.0
* Operating System: MacOS
* Graphics Card: Intel
* Browser: Chrome 57.0.2987.133 (64-bit)
* VR Device: 暴风魔镜S1

**Comment by andrewimm** [comment]
Can you go into your node_modules directory and confirm what the version numbers are for `react-vr` and `fbjs`?

**Comment by handoing** [comment]
@andrewimm 
`react-vr` version is 1.0.0 in node_modules directory, but I did‘t find `fbjs` package.

It will help ？
Client：
This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`

**Comment by andrewimm** [comment]
Please install a version of `npm` greater than or equal to 3.0.0, and try again. This is usually because your `npm` is out of date.

**Comment by handoing** [comment]
Thanks!
I updated the `npm` version from 2.x.x to 4.5.0.
The issue is resolved.

**Comment by karmaggyatso** [comment]
I'm facing the similar issue. my npm version is 6.2.0 and fbjs is   "version": "0.8.17". please advise
