### ISSUE TITLE
Can play video on browser for android

### ISSUE THREAD

**Issue by huangbuyi** [facebook/react-vr#117]
As we know, there's auto-play restricted on mobile, so I try to use `Video` or `VideoPano` to set a vr video (mp4 type) and `MediaPlayerState` to play it , it work good on PC, but unwork on Chrome(v58) or Firfox(v53) of my android(v5.1) device. 

![](http://onw3okkga.bkt.gdipper.com/react_vr_vedio.jpg)

**Comment by larrylin28** [comment]
AutoPlay is restricted on mobile, but I think you can auto-play a muted video on android. Also, for unmuted video, you can press the play button of VideoControl to play it.

**Comment by igghera** [comment]
Hi, I tried yesterday on Chrome + Nexus 5X and a `VideoPano` with `muted` + `autoplay` doesn't actually autoplay, not sure what I'm doing wrong. Here's my code:
```
import React from 'react';
import { AppRegistry, asset, StyleSheet, Pano, VideoPano, View, MediaPlayerState } from 'react-vr';

export default class WelcomeToVR extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      playerState: new MediaPlayerState({ autoPlay: true, muted: true })
    };
  }

  render() {
    return (
      <View>
        <VideoPano
          playerState={this.state.playerState}
          source={{ uri: '/static_assets/video.mp4' }}
        />
      </View>
    );
  }
}

AppRegistry.registerComponent('WelcomeToVR', () => WelcomeToVR);

```

**Comment by larrylin28** [comment]
Hi, what's your Chrome version? 
The autoPlay for muted video is only supported after version 53.

**Comment by igghera** [comment]
I'm on Chrome 58

**Comment by larrylin28** [comment]
I tried your code and it works fine on my device. It would be appreciate if you can grap some log on your device by `adb logcat | grep chromium`. It would help us understand the issue.

**Comment by igghera** [comment]
Absolutely, I'll do it asap and reply here. 
Just out of curiosity, the `autoplay` worked?

**Comment by larrylin28** [comment]
@igghera yes, the video auto played on Chrome for Android.

**Comment by igghera** [comment]
I guess it all comes down to this (the last rows in the log):

```
chromium: [INFO:CONSOLE(42002)] "Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.", source: http://localhost:8081/vr/client.bundle?platform=vr (42002)

chromium: [INFO:CONSOLE(42002)] "Uncaught (in promise) NotAllowedError: play() can only be initiated by a user gesture.", source: http://localhost:8081/vr/client.bundle?platform=vr (42002)
```

**Comment by larrylin28** [comment]
That's weird. Have you try opening a web page contains `<video src="static_assets/video.mp4" autoplay muted>` and see if it auto play on your mobile phone?

**Comment by igghera** [comment]
Tried now: it doesn't autoplay on my Android, though it does on my mac (always on Chrome)

**Comment by larrylin28** [comment]
@igghera Then it seems to be a problem of your Chrome. Chrome should support autoplay video since version 53. Try update your  Chrome and Android, if you still have problem, try report to chromium issues: https://bugs.chromium.org/p/chromium/issues/list

**Comment by igghera** [comment]
Yeah it does look like a problem with Chrome, even though it's weird because I'm on version 58.
I'll report this to Chromium.
Thanks a lot for your support!

**Comment by infoxiao** [comment]
@larrylin28 Have you had any success when viewing in the headset? I got the VideoPano to work on mobile, but it went into a blank screen when I click 'View in VR' and put on a headset.

**Comment by darioodiaz** [comment]
I had the same problem but it was by a configuration that I set, when I saw my Chrome settings (Chrome -> Settings -> Site Settings -> Media) few weeks ago I block autoplay videos, so you should review your settings to see if you didnt do the same as I. By the way the default settings is autoplay muted videos, I enable autoplay again and I can use VideoPano with a muted video

**Comment by infoxiao** [comment]
Looks like Oculus browser now supports video with sound! Closing this issue.
