### ISSUE TITLE
Yarn instructions incorrect

### ISSUE THREAD

**Issue by samskivert** [facebook/react-vr#120]
### Description

The instructions on the main page are incorrect:

```
% yarn global install react-vr-cli
yarn global v0.23.2
error Invalid subcommand. Try "add, bin, ls, remove, upgrade, upgrade-interactive"
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

what I think you want is:

```
yarn global add react-vr-cli
```

#### Expected behavior

N/A

#### Actual behavior

N/A

### Reproduction

See above.

### Solution

See above.

### Additional Information

* React VR version: N/A
* Operating System: Mac OS but probably N/A
* Graphics Card: N/A
* Browser: N/A
* VR Device: N/A

**Comment by petetnt** [comment]
Dupe of #121 and #101 😹

**Comment by samskivert** [comment]
Alas,  searched the issues (for the word yarn which yielded 0 results) before reporting. But I guess 101 was closed even though the README had not yet been updated.
