### ISSUE TITLE
render JWplayer using reactVR

### ISSUE THREAD

**Issue by Sangath** [facebook/react-vr#122]
I am trying to render JWplayer inside the scene using HTMLmixer library. https://github.com/jeromeetienne/threex.htmlmixer

But I don't see a possible way to add external library to the ReactVR project. Is there anyway to do it?
Also, Is there any alternative way to render JWplayer inside the scene?

**Comment by Ninerian** [comment]
From the description I think it won't be possible to use that library, as it uses CSS3D to transform HTML Elements to look like they are part of the scene.  

This works, as long as you don't go stereoscopic. Besides this it would also cause a huge performance drop.  

To integrate videos, there is the video component. But if you intend to show YouTube videos into the scene, you have to find a Threejs Element which provides this feature.  

For the implementation in ReactVR look in the ovrui library.  

Aframe provides some out of the box solutions for rendering HTML in webgl. Maybe this suits more your needs.

**Comment by Sangath** [comment]
Thanks for the response @Ninerian . I will look into it
