### ISSUE TITLE
Include THREEjs video texture - VideoJS

### ISSUE THREAD

**Issue by steverob** [facebook/react-vr#124]
Here is an example of a HLS video being rendered in a ThreeJS scene using VideoJS - https://jsfiddle.net/vm4detdy/

I assume inorder to use this in ReactVR, I'll need to follow this - https://facebook.github.io/react-vr/docs/native-modules.html

Little confused though. Would love some pointers. Thanks :)

**Comment by mikearmstrong001** [comment]
Thanks, let's see what we can do to fit under the current systems and the extensions to support videos rather than add a new native module.

We'll use https://d2zihajmogu5jn.cloudfront.net/bipbop-advanced/bipbop_16x9_variant.m3u8 as an example url

**Comment by larrylin28** [comment]
There's a function `setCustomizedVideoPlayer` which offers a way to use any customized video player to play video in ReactVR. A customized video player should extends `BasicVideoPlayer`. Here's an example of using `VideoJS`, you can put this in `vr/client.js` generated by cli.

`
import {setCustomizedVideoPlayer, BasicVideoPlayer} from 'OVRVideo';

/**
 * The HLS video player
 */
class HLSVideoPlayer extends BasicVideoPlayer {
  constructor() {
    super();
    this.source = document.createElement('source');
    this.videoElement.appendChild(this.source);
  }

  initializeVideo(src: string, metaData: any) {
    this.source.setAttribute('src', src);
    this.source.setAttribute('type', 'application/x-mpegURL');
    this.videoElement.crossOrigin = 'anonymous';
    this._bindMediaEvents();
    this.player = videojs(this.videoElement);
  }
}

function init(bundle, parent, options) {
  setCustomizedVideoPlayer(HLSVideoPlayer);
`

**Comment by steverob** [comment]
@larrylin28 awesome and then I just use the builtin `Video` component?

**Comment by steverob** [comment]
@larrylin28 do I need to install `ovr-video` separately?  Getting this - 

```
UnableToResolveError: Unable to resolve module `OVRVideo`
```

**Comment by agsirex** [comment]
Delet plese lunedì, 24 aprile 2017, 07:00PM +02:00 da Steve Robinson  notifications@github.com :

**Comment by larrylin28** [comment]
@steverob, it seems they are not exported, I'll put up a change to export them.

**Comment by steverob** [comment]
That would be so helpful 

--
Regards
Steve Robinson

**Comment by larrylin28** [comment]
@steverob Here's the doc for hooking customized video player
