### ISSUE TITLE
Can I translate the docs to Simplified Chinese?

### ISSUE THREAD

**Issue by juzhiyuan** [facebook/react-vr#131]
### Description
 >Feature Request

I'd love to translate the docs to Simplified Chinese, Can I claim this task?

Ok then I'll pull a request.

**Comment by amberroy** [comment]
Translating the docs would be great.  There is already some work done on this, see Issue https://github.com/facebook/react-vr/issues/75 and http://webvrcn.org/react-vr/#/

**Comment by juzhiyuan** [comment]
yeah It'll be great to share the amazing VR with us Chinese,thanks a lot.

**Comment by juzhiyuan** [comment]
@amberroy I suggest you can add the [webvrcn link](http://webvrcn.org/react-vr/#/) to an Eye-catching location.
