### ISSUE TITLE
npm test fails on init project

### ISSUE THREAD

**Issue by DeDuckProject** [facebook/react-vr#132]
### Description
npm test on init project doesn't pass. It looks for `Mesh` in setup.js instead of `Model`
#### Expected behavior
test to pass
#### Actual behavior
```sh
$ npm test

 FAIL  __tests__/client.js
  ● Test suite failed to run

    Cannot find module 'Mesh' from 'setup.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-vr/jest/setup.js:22:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.89s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```
### Reproduction

run react-vr init proj -> yarn -> npm test

### Solution
fix suggested here:
https://github.com/facebook/react-vr/pull/123/commits/f9c2b537ee5b60ec45d2c6b5fb3aaa72d45f7f3e

### Additional Information

* React VR version: 1.0.0
* Operating System: macOS

**Comment by amberroy** [comment]
Thank you for catching this!  We will merge your fix.

**Comment by DeDuckProject** [comment]
Thanks Amber

**Comment by agsirex** [comment]
lunedì, 24 aprile 2017, 09:30AM +02:00 da Iftach Yakar  notifications@github.com :

**Comment by DeDuckProject** [comment]
merged
1c1424bb9aaa7903ef82f99cc8b7dd0cc4f57a50

**Comment by infiniteluke** [comment]
This issue still exists 

`react-vr init testing && cd testing && yarn test`

```bash
$ npm t
 FAIL  __tests__/client.js
  ● Test suite failed to run

    Cannot find module 'Mesh' from 'setup.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-vr/jest/setup.js:22:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.983s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

I noticed 1c1424b made it in but not f9c2b53 which fixes this issue. Happy to PR if necessary.

Thanks for your work on this project 👍 😄

**Comment by DeDuckProject** [comment]
You are right, I'll PR again now. Thanks
