### ISSUE TITLE
Where are the samples located? (cubesample, toursample )

### ISSUE THREAD

**Issue by chribbe** [facebook/react-vr#140]
### Description

Where are the samples located? At some places the Docs is referring to sample projects that I can't find. For example the "cube sample" here:
https://facebook.github.io/react-vr/docs/native-modules.html

Maybe the samples are outdated and replaced by the examples? if so it would make sense to update the docs.

**Comment by mikearmstrong001** [comment]
The samples have moved to examples so that they can be placed in GitHub. We'll be adding more as questions come up. We'll make a specific native module example available.

**Comment by agsirex** [comment]
lunedì, 24 aprile 2017, 10:18AM +02:00 da Mike Armstrong  notifications@github.com :
