### ISSUE TITLE
_reactNative.Platform.select is not a function

### ISSUE THREAD

**Issue by ComradePashka** [facebook/react-vr#145]
Hello!

I am trying to use simple piece of code from example:
https://facebook.github.io/react-vr/docs/platform-specific-information.html#platform-module

#### Expected behavior
value substitution depending on current platform

#### Actual behavior
error message in dev console `_reactNative.Platform.select is not a function`

### Reproduction
any call to Platform.select()

### Additional Information
console.log(Platform) shows: `Object {OS: "vr"}` so attribute `OS` is available

* React VR version: 4.2.0
* Operating System: Win10
* Graphics Card: NVidia GT 620M
* Browser: Chrome 58.0.3029.81 (64-bit)
* VR Device: None

**Comment by andrewimm** [comment]
Platform.select, while written as a function, is not actually a function in your final compiled code. It actually gets inlined at build time into whatever expression it should be.
It appears that the transform pipeline isn't performing the inlining properly. I'll look into it and make sure we're piping the platform key that deep into the packager.

Can you provide the code that fails? I'd like to see how you're importing Platform

**Comment by andrewimm** [comment]
I guess I had confused the inlining of production builds with the transforms used for development builds. This is resolved in 9e92f102b7f2f861e5b801fdbd5986fd58a405d9, and will be available in the 1.1.0 release later this week.
