### ISSUE TITLE
react-vr init can not init success

### ISSUE THREAD

**Issue by Edwardelric** [facebook/react-vr#147]
when I run  react-vr init  reactvr, it's failed and have some error tips:

yarn install v0.21.3
info No lockfile found.
[1/4] 🔍  Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/babel-plugin-transform-es2015-classes: 140736586900416:error:1408F119:SSL routines:SSL3_GET_RECORD:decryption failed or bad record mac:../deps/openssl/openssl/ssl/s3_pkt.c:532:\n".
info If you think this is a bug, please open a bug report with the information provided in "/Users/apple/workspace/hardlearn/reactvr/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
`yarn` exited with code 1. Try fixing the errors above and run `yarn` from within reactvr again

how can I  fix this problem?

**Comment by andrewimm** [comment]
According to the error message, `yarn` is having a problem downloading one of the dependencies. This is unrelated to React VR.

I'd first recommend updating Yarn to the latest version. If that still fails, your project has already been initialized, so you can set up the dependencies by running `npm install` from within the project.
