### ISSUE TITLE
Cursor appears to be too small to render

### ISSUE THREAD

**Issue by bakkerme** [facebook/react-vr#149]
### Description

I've been trying to figure out why the cursor won't render even if `cursorVisibility: 'visible'` is set. I found that in [GuiSys, the cursor width is set pretty low.](https://github.com/facebook/react-vr/blob/95445e0e05a971a4873ba8bdc701f32ec0765ea5/OVRUI/src/UIView/GuiSys.js#L41) I had to set it to around .3 before the cursor would show up, both outside VR and inside on my Cardboard setup.

#### Expected behavior

The cursor should be visible when needed.

#### Actual behavior

The cursor is not visible.

### Reproduction

1. Set `cursorVisibility: 'visible'` in the VRInstance options
2. Use a raycaster that renders a cursor (I used a simple gaze raycaster)
2. Open a completely empty scene. You will not see a cursor.

### Solution

I'm not sure what size is considered correct here. On my device .5 is pretty good, but I'm assuming this would change across devices, depending on the resolution.

### Additional Information

* React VR version: react-vr: 1.0, react-vr-web, 1.0
* Operating System: Windows 10
* Graphics Card: AMD Radeon 380x
* Browser: Chrome 57.0.2987.133 on PC, Chrome Canary 60.0.3077.0, Cardboard
* VR Device: Google Cardboard style headset with a Moto X Force, Android 6.0. Issue is both in VR and the non-vr viewer

**Comment by andrewimm** [comment]
Can you provide a screenshot, and your raycaster code? Cursors in all my tests appear to be a reasonable size (about 0.5cm on a Pixel)

**Comment by bakkerme** [comment]
I did some extra experimentation and turns out it was an implementation issue in my raycaster. I had assumed that the z value was intended to be the max distance that an intersection could occur. Upon setting it to -1 the cursor was visible. Sorry to bother you.

**Comment by andrewimm** [comment]
That's okay, we can improve from this as well. We should consider normalizing the direction of the vector within GuiSys, so that this confusion doesn't happen.
