### ISSUE TITLE
[Question] How to scroll screen on mobile browser, like on desktop browser?

### ISSUE THREAD

**Issue by lwd369** [facebook/react-vr#151]
### Description

On desktop browser I can use mouse to scroll screen. 

But on my mobile device's browser, I can't use finger to scroll the screen , what only I can do is using gravity sensor to see the whole scene. 

Somebody know how to use finger to scroll screen on mobile browser?

### Additional Information
* React VR version: react-vr version 1.0.0, react-vr-web 1.0.0
* Operating System:iOS10.3.1
* Browser: Mobile Chrome57.0.2987.137 on iOS
* VR Device: No headset

**Comment by amberroy** [comment]
Currently it is not possible to scroll the screen on mobile, however this is a feature we plan to add.  

Tell me more about your use case. Imaging that you could scroll to more the camera on mobile, once you start scrolling do you want to stay in "scroll mode" for that app, or do you also want to be able to return to the orientation tracking (gravity sensor) mode when done scrolling?

**Comment by mathdroid** [comment]
@amberroy Can we do both? If I'm not mistaken, the behavior of 360 image/video in Facebook is using both scroll and accelerometer. But I think it only registers Y-axis rotation for the scroll.

**Comment by lwd369** [comment]
@amberroy thanks for your answer.

In my use case, I'm working on a VR project which running on mobile browser(withou VR headset ). I wanna user can explore the scene via both scrolling  and orientation tracking. The orientation tracking should be disabled when user start scrolling, and once user stop scrolling the orientation tracking should be restore automatically.

Imagine that if user want to see the behind scene,they must turn 180 degree round with their cellphone. It's pretty wierd. I think VR on mobile (without VR headset) the scroll feature is important.

**Comment by amberroy** [comment]
Added in **Add pinch-to-zoom on mobile.** (addb42a) 
See also **Add touch panning on mobile.**(fc01746)

**Comment by bbtran** [comment]
Hoping someone can help me with how to zoom in general? Is there a specific equivalent to onScroll?  
I'm new to react-vr and am having difficulty with getting the camera to zoom in and out using mouse wheel. Any tips would be helpful! Thanks!

**Comment by vinhub** [comment]
Is this expected to let you touch pan in the vertical direction also? It looks like it only does horizontal.
