### ISSUE TITLE
Is Running React VR requires Internet connection?

### ISSUE THREAD

**Issue by sv955** [facebook/react-vr#152]
We use GitHub Issues for bugs and support tracking for the preview

--- Please use this template, and delete everything above this line before submitting your issue ---

### Description

[FILL THIS OUT: Bug or Feature Request? For a Bug please explain what you did, what you expected to happen, and what actually happens. Sections below]

### Reproduction

[FILL THIS OUT: Try to reproduce your bug in a minimal example, maybe you could alter one of the samples to demonstrate the problem]

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide source code or a patch with a fix.]

### Additional Information

* React VR version: [FILL THIS OUT: both react-vr and react-vr-web]
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?]
* Graphics Card: [FILL THIS OUT: NVIDA, ATI, Intel? Which Driver?]
* Browser: [FILL THIS OUT: Carmel, Chrome, Edge, Safari? Which version?]
* VR Device: [FILL THIS OUT: In or Out of VR? Headset? ]

**Comment by andrewimm** [comment]
React VR requires that you have a connection from your web browser to a computer serving your code. That can be a local network, the internet, or something else.
