### ISSUE TITLE
"audioModule.unload is not a function" after changing the source of the sound

### ISSUE THREAD

**Issue by HeinPauwelyn** [facebook/react-vr#154]
### Description

I'm building an application using React VR and will set a background sound on the scenes. This sound must change dependent of the actions of the user. I play the sound with this code:

```jsx
<Sound source={{ mp3: asset(`audio/${this.state.active.sound}`) }} 
       loop={true} 
       volume={0.5}></Sound>
```

If I update the variable `this.state.active.sound` using code below:

```jsx
this.setState({
    active: {
        sound: "other-sound.mp3"
    }
});
```

The previous sound will continue playing till it's ended.

I've also got this error message:

> Uncaught TypeError: `audioModule.unload` is not a function

I've also tried to make an array of `Sound`-JSX-tags and change the volume of each element to zero but didn't change anything.

Do you have any sugestions for me?

#### Expected behavior

Sound one is unloaded and `other-sound.mp3` is playing.

#### Actual behavior

After navigating, sound one will continue playing till it's ended. `other-sound.mp3` will start to play together with sound one.

### Additional Information

* React VR version: 0.2.0
* Operating System: all
* Graphics Card: all
* Browser: all
* VR Device: all

**Comment by larrylin28** [comment]
I tried to reproduce with no luck. Would you mind offering more detail of your code?
Also please update to latest version.

**Comment by HeinPauwelyn** [comment]
[Here is a link to the most important parts of my code](https://gist.github.com/HeinPauwelyn/2c9b0c6199cae14566968256f8ae439a). The full project is not possible.

**Comment by larrylin28** [comment]
I just created a project, put your code in and test. I can't see any error, when I click on the red sphere, the background photo and sound changed correctly.
Can you try pull the latest master, clean up the node module and do `npm install` again?

**Comment by HeinPauwelyn** [comment]
Solved. I was using react vr version 0.2.0 instead of 1.0.0

Thanks for helping 😄
