### ISSUE TITLE
"View in VR" doesn't work after SteamVR update

### ISSUE THREAD

**Issue by freemanon** [facebook/react-vr#159]
Can't seem to switch to VR mode after updating to the latest SteamVR.

Hardware: Vive
SteamVR version: Apr 20, version 1492726420

**Comment by freemanon** [comment]
Found a temporary fix from the Chrome WebVR repo:
https://github.com/toji/chrome-webvr-issues/issues/135#issuecomment-278556238

**Comment by andrewimm** [comment]
This sounds like a Chrome Experimental issue, not a React VR issue, so I'm going to close this out.
