### ISSUE TITLE
Tokbox - WebRTC

### ISSUE THREAD

**Issue by steverob** [facebook/react-vr#162]
Hi,

I'm wondering if it's possible to render video elements like this - https://tokbox.com/developer/guides/customize-ui/js/#video-element within ReactVR. Any pointers how I start with this please? Thanks

**Comment by steverob** [comment]
Specifically, can you check this out - https://github.com/josecpujol/opentok3d/blob/master/views/3dLayoutThreeJs.ejs#L347 

Would like to just know if this is something possible with the current state of ReactVR or should I take a different approach? Thanks.

**Comment by steverob** [comment]
Can I implement a version of `BasicVideoPlayer` that takes in a videoElement as a source?

**Comment by larrylin28** [comment]
Yes.
I'm working on a full example and documentation to show how to write your own video player and hook into React VR. Will be there soon.

**Comment by larrylin28** [comment]
Here's the doc for hooking customized video player
https://facebook.github.io/react-vr/docs/video-player.html
