### ISSUE TITLE
How to set sphere opacity

### ISSUE THREAD

**Issue by light564** [facebook/react-vr#164]
* React VR version: 1.0

**Comment by andrewimm** [comment]
Try setting
```
style={{
  opacity: SOME_OPACITY,
}}
```

**Comment by mikearmstrong001** [comment]
@light564 you are correct there is a missing setting. I've resolved in an up and coming change.

@andrewimm's example will be how you will you the setting

**Comment by light564** [comment]
@mikearmstrong001  it's looks great. But i have another question.

my code: 
```
<View 
  style={{
    opacity: 0.1
  }}>
    <Sphere />
</View>
```

What should the Sphere look like? There any opacity in Sphere?

React VR version: I update react-vr-web code.

**Comment by light564** [comment]
There are a warning: Failed prop type: Invalid props.style key `opacity` supplied to `Plane`.
what should i do.

**Comment by mikearmstrong001** [comment]
Sorry I missed that in testing, this is a check in the style proptypes. fix incoming.

Opacity has been propagated to 3d models like image and text views. I've had mixed feelings about this in the past, can you define your use case of this behavior?
