### ISSUE TITLE
Pano image shifts during state transition

### ISSUE THREAD

**Issue by infoxiao** [facebook/react-vr#173]
### Description
I have rendered a panorama image, in it I have text and VrButtons. What I want to do is once the user clicks on the button, I will transition to next "screen" -- meaning a different set of text and VrButtons. My current implementation is fine except for that when the state transitions, the <Pano> image seems to shift, resulting in a non-smooth transition.

Wondering how to make a smooth transition instead.

#### Expected behavior
I am using a state to represent different screens. So this is my current setup:

```
export default class main extends Component {
  constructor(){
    super();
    this.state = {
      stage: 'screen1',
    };
  }
  renderScreen1(){
  	return(
  		...
  		<View> text and buttons (on button click set this.state.stage to "screen2")
  		</View>
  	);
  }
  renderScreen2(){
  	return(
  		...
  		<View> text and buttons
  		</View>
  	);
  }
  render(){
  	return(
          <View>
              <Pano source={asset(this.state.roomImage)}/>
              {this.state.stage=='screen1'? this.renderScreen1() : null}
              {this.state.stage=='screen2'? this.renderScreen2() : null}
           </View>
  	);
  }
}
```

Not sure if this is the best way to do it. If not please point out.

#### Actual behavior
If my setup has no problem. The <Pano> image should not move. But for some reason, when screen 2's button and text appears, the <Pano> seems to have shifted.

I am using translate [x, y, z] for views as well as setting `layoutOrigin: [0.5, 0.5]`. Maybe the shifting has something to do with the layoutOrigin setup? I can't seem to make sense yet out of the 3D coordinates doc. So any pointers would be appreciated.

Thanks a lot.

**Comment by mkeblx** [comment]
Does setting `style={{position: 'absolute'}}` on `Pano` modify behavior?

**Comment by mikearmstrong001** [comment]
`style={{position: 'absolute'}}` is the default setting for `Pano` so that should modify the behaviour

Can you detail a little more of the shift you see? 
Does the shift happen if you change the `stage` but not the `roomImage` ?

**Comment by infoxiao** [comment]
@mkeblx tried it. The shift is still there.
@mikearmstrong001 I made a screen capture:
https://vimeo.com/216030327
Note that at 4'', the room gets distorted.
This is the button that triggered this distortion. One problem with transitioning different images is that the text always renders before the image loads. So I set a ``transition`` stage which basically does nothing, then set a timeout to render the next stage of the texts. I was hoping the pano image won't shift...
```
<View style={{width: mywidth}}>
  <VrButton disabled={this.state.readyToEnter? false : true}
    onClick={() => { this.setBackgroundImage(this.state.conditionRoom);
                     this.setState({stage: 'transition'});   
                     setTimeout(function(){this.setState({stage: 'walkInRoom'});}.bind(this), 3000);
                    }
            }>          
    <HighlightView height={45} text={this.state.readyToEnter? 'Enter' : 'Enter (Disabled)'} backgroundColor='grey'/>
  </VrButton>
</View>
```

Then at 18'', 22'', you can also see the pano image shifts slightly, where I believe I was just changing the ``stage`` but not the ``roomImage``.

Thank you!

**Comment by Cosmitar** [comment]
Based on the video, seems like your state change is rendering again the main view and therefore the camera is restored to initial settings, causing that jump.
