### ISSUE TITLE
Component looks different for each reuse.

### ISSUE THREAD

**Issue by HeinPauwelyn** [facebook/react-vr#174]
### Description

I'm trying to make some buttons that must look like on image below.

![image](https://cloud.githubusercontent.com/assets/16222780/25657870/4c094006-3000-11e7-8c1e-41430c4dd149.png)

#### Expected behavior

I'm expecting that every component looks the same like on image above.

#### Actual behavior

But it isn't. Look like images below:

![image](https://cloud.githubusercontent.com/assets/16222780/25658221/17b07584-3002-11e7-8409-671f75c33327.png)
![image](https://cloud.githubusercontent.com/assets/16222780/25658233/275a181e-3002-11e7-93f2-984346f67e2d.png)
![image](https://cloud.githubusercontent.com/assets/16222780/25658261/44e202fc-3002-11e7-821c-ea6ca4e869e3.png)

### Reproduction

For this I'm using code below:

```jsx
<View 
    style={{ 
        transform: [ 
            { translate: this.props.to.translate }, 
            { rotateX: this.props.to.rotation[0] }, 
            { rotateY: this.props.to.rotation[1] }, 
            { rotateZ: this.props.to.rotation[2] }, 
            { scale: this.props.to.scale } 
        ] 
    }}>

    <VrButton 
        onEnter={()=> { 
            this.animateButton(this.props.to, true); 
        }} 
        onExit={() => { 
            this.animateButton(this.props.to, false); 
            this.setState({ gazeCurrent: 0 }); 
        }}>
        
        <Sphere 
            radius={0.5} 
            widthSegments={10} 
            heightSegments={10} 
            style={{ 
                color: 'red'
            }}>
        </Sphere>
        <Image 
            source={asset('assets/navigationCircle.png')} 
            style={{ 
                height: 2,
                width: 2
            }}>
        </Image>
    </VrButton>
</View>
```

Here is the code where I render the components:

```jsx
render() {
    return (
        <View>
            <Pano source={asset(`360 LR/${this.state.active.pano}`)} />
            {this.renderNavigationButtons()}
        </View>
    );
}

renderNavigationButtons() {
    let navButtons = [];
    for (let i = this.state.active.navigations.length; i--;) {
        let el = this.state.active.navigations[i];
        navButtons.push(
            <NavigateButton
                key={el.to}
                to={el}
                navigate={() => this.onNavigating(el.to)}
            />
        );
    }

    return navButtons;
}
```

### Solution

I've tried to replace the `Image`-tag from code above with code below and give an extra component named `transform`.

```jsx
<Image 
    source={asset('assets/navigationCircle.png')} 
    style={{ 
        height: 2,
        width: 2,
        translate: [
            { transform: this.props.to.transformImage /* this is unique for each image. */ }
        ]
    }}
/>
```

### Additional Information

* React VR version: 1.0.0
* Operating System: All
* Graphics Card: All
* Browser: all browsers, all versions
* VR Device: In and out of VR? all headsets

**Comment by mikearmstrong001** [comment]
do you want the sphere to follow the layout rules of flex box ?
3D objects (such as sphere) has the style.position set to 'absolute' if you want them to layout with other 2d elements you will need to set the style to 'relative' and provide a style width and height.

Out of interest is the 3d sphere important to you? as performance would be a better with a simple 2d image representation

Let me know if this helps you.

**Comment by HeinPauwelyn** [comment]
It works after trying some thing. This is my new code

```jsx
<Image
    source={asset('assets/navigationCircle.png')}
    style={{
        height: 2,
        width: 2,
        transform: [
            { translate: [-1, 1, 0] }
        ],
        position: 'absolute'
}}>
```

Also the sphere is has a absolute position.

The sphere I use was before I've added the image around it. It was just easier for me because you don't have to rotate it. On all sides a sphere looks like the same circle. Indeed now it not really needed that I use that sphere. In a next version, I go change that into an 2D image like you said.

Thanks for the tip. 😄
