### ISSUE TITLE
About DASH Support on Carmel Browser for Gear VR

### ISSUE THREAD

**Issue by alexduros** [facebook/react-vr#176]
### Description

This is more a question than an issue about video format support on VR Browsers such as Carmel Browser.
There is an Example on a [Dash Player][1] which is working on Chrome 57. 

But I can't figure out if this could be working on Carmel Browser for the Gear VR since this browser does not seem to be supported any codec used in [sample dash 360 content][3]. 

Since I can't really find any ressource on technical specification on this browser to know if this will be supported in the future. `MediaSource.isTypeSupported` seems to returns false for all kind of codecs. I know this is not directly linked to react-vr but I thought it would be interesting to address it here.

Actually, I'm working on a PR to provide the same kind of example but for HLS contents using [hls.js][2]

### Additional Information

* Browser: [Carmel]
* VR Device: [Gear VR]

[1]: https://github.com/facebook/react-vr/tree/master/Examples/DashSample/vr
[2]: https://github.com/video-dev/hls.js
[3]: https://bitmovin-a.akamaihd.net/content/playhouse-vr/mpds/105560.mpd

**Comment by nfurtwangler** [comment]
Are you using Carmel Developer Preview, or the newly released Oculus Browser?

Developer Preview did not have many of the codecs available.

Oculus Browser should have the same set of codecs as Chrome for Android.

I am getting 'true' for this check for example:

MediaSource.isTypeSupported('video/mp4; codecs="avc1.42c00d"')

**Comment by alexduros** [comment]
Indeed, @nfurtwangler, I did test with the Developer Preview.
In order to be able to play video (HLS with hls.js) with Gear VR and Oculus Browser, I had to disable a flag via `chrome://flags` to disable the feature which disable possibility call `videoElement.play` without a user action, since in react-vr, the user event seems to be lost by the EventEmitter.

**Comment by DigiTec** [comment]
We are working on a standards compliant solution for Oculus Browser that should allow you to start video based on a user interaction related to the VR events. Specifically we plan to implement the user interaction requirement for vrdisplayactivate.

I suspect that this will hit the public release sometime between mid to late June. If I get an updated schedule that changes this I'll try to keep this thread updated.

**Comment by larrylin28** [comment]
@alexduros Here's the doc for hooking customized video player
https://facebook.github.io/react-vr/docs/video-player.html
Which may help on your hls player

**Comment by alexduros** [comment]
Thanks @larrylin28, I have a hls working example, I will a create a PR with this stuff ASAP.
