### ISSUE TITLE
3D transforms doc has some error

### ISSUE THREAD

**Issue by light564** [facebook/react-vr#177]
[transform properties](https://facebook.github.io/react-vr/docs/3dcoordinates-and-transforms.html#transform-properties)
```
// in matrix
rotation can be represented the R values in [R00, R01, **R02**, ...]
```
And the R value is the same as [Rotation matrix](https://en.wikipedia.org/wiki/Rotation_matrix#General_rotations) ?

**Comment by andrewimm** [comment]
Our documentation is open source! Feel free to submit a pull request

**Comment by bnaveenkr** [comment]
Hey @andrewimm I have created a PR to fix this https://github.com/facebook/react-vr/pull/184

Thanks!
