### ISSUE TITLE
How customize React vr component

### ISSUE THREAD

**Issue by light564** [facebook/react-vr#178]
How to make a React vr compoent. ex: Line.
I don't know how to import RCTBaseMesh.

**Comment by amberroy** [comment]
We have a Plane component that could be used to simulate a line, if you make it very thin.  :)  To make a Line component you would follow the example of the Box and add code to both the runtime and the React side: 
https://github.com/facebook/react-vr/blob/master/ReactVR/js/Views/Plane.js
https://github.com/facebook/react-vr/blob/master/Libraries/Mesh/Plane.js

Does this address your use case?

**Comment by light564** [comment]
I should make a line.js in ReactVR and Libraries? But not in my project?

**Comment by mikearmstrong001** [comment]
a single line is very low level, it seems you would need many for the component to be useful. Is this correct for your usecase.

For our native React VR I implemented a model based on subset of a SVG path definition this seems a more useful component. Agreed ?

**Comment by light564** [comment]
OK, i will use model to finish my project.(sorry for my poor english)
