### ISSUE TITLE
Building Fontue tool to generate font set for ReactVR - path_utils.h missing

### ISSUE THREAD

**Issue by chribbe** [facebook/react-vr#182]
From the React VR Docs: https://facebook.github.io/react-vr/docs/fonts.html

> It is also possible to generate your own font set textures using the fontue tool in the Oculus Mobile SDK. The tool has a dependency on FreeType, and can be found in the Oculus Mobile SDK Tools/fontue directory, along with a readme.txt describing its operation.

When trying to build the fontue tool in Visual Studio we're getting an error on this include:

include "../common/path_utils.h"

I can't find the path_utils.h in the Oculus Mobile SDK anywhere. Is it supposed to be included somewhere in the package or am i missing something else?

This question was also posted to stackoverflow:
https://stackoverflow.com/questions/43783005/building-fontue-tool-to-generate-font-set-for-reactvr-path-utils-h-missing

**Comment by mikearmstrong001** [comment]
I've ported fontue to a standalone tool outside of Mobile SDK and compilable on Mac. Please bear with me to see if I can release in some form.

**Comment by chribbe** [comment]
That would be great!

**Comment by mikearmstrong001** [comment]
Looks like I have the necessary boxes ticked so expect progress :)

**Comment by chribbe** [comment]
Great! Looking forward to test it

**Comment by lwd369** [comment]
I also had the same problem. I want to generate custom font set, but it seems can't do that by now.
And I use Hiero to generate SDF font , it can used in a-frame but can't used in react-vr.

**Comment by andrewimm** [comment]
Mike shipped this tool, it can be found at https://github.com/facebook/react-vr/tree/master/tools/fontue
