### ISSUE TITLE
npm package dependencies missing

### ISSUE THREAD

**Issue by mkeblx** [facebook/react-vr#185]
### Description

I get the following after doing a `npm install`, on a couple different setups, mac & linux.
```
npm WARN eslint-config-fbjs@1.1.1 requires a peer of babel-eslint@^6.1.2 but none was installed.
npm WARN eslint-config-fbjs@1.1.1 requires a peer of eslint-plugin-babel@^3.3.0 but none was installed.
npm WARN eslint-config-fbjs@1.1.1 requires a peer of eslint-plugin-react@^5.2.2 but none was installed.
```

#### Expected behavior
Install fully without without not-installed warnings.
#### Actual behavior
Above.
### Reproduction

Fresh `npm install`  &middot; Ubuntu 16.04, node 7.10, npm 4.2; `master`

### Solution
Update package dependencies

### Additional Information

* React VR version: [react-vr]
* Operating System: [MacOS, Linux]
* Browser: [N/A]
* VR Device: [N/A]

**Comment by andrewimm** [comment]
This is expected. `eslint-config-fbjs`, which is an external dependency, has explicit expectations for older versions of those packages. We use newer ones with no issues. These warnings can be safely ignored.

**Comment by mkeblx** [comment]
Okay. Are you using the package.json script for flow? `npm run flow` gave me this:

```
react-vr-cli/index.js:15
 15: const chalk = require('chalk');
                   ^^^^^^^^^^^^^^^^ chalk. Required module not found
```

**Comment by andrewimm** [comment]
`react-vr-cli` is a subpackage that requires its dependencies to be installed from that directory. If all dependencies are installed, it will succeed. Flow runs on each of our CI test passes: https://circleci.com/gh/facebook/react-vr, the master branch is currently green.

But thanks for trying to troubleshoot some perceived errors!
