### ISSUE TITLE
Sound of React VR Components doc has some error

### ISSUE THREAD

**Issue by gxnews8** [facebook/react-vr#188]
### Example usage:
<Image style={{height: 2.0, width: 2.0}} source={uri: 'images/waterfall.jpg'}>
  <Sound source={uri: 'sounds/waterfall.wav'}>
</Image>
### Should be:
<Image style={{height: 2.0, width: 2.0}} source={uri: 'images/waterfall.jpg'}>
  <Sound source={uri: 'sounds/waterfall.wav'} />
</Image>
### https://facebook.github.io/react-vr/docs/sound.html

**Comment by andrewimm** [comment]
Our documentation is open source! Feel free to submit a PR, we'll be happy to accept it.

**Comment by mikearmstrong001** [comment]
thank you!
