### ISSUE TITLE
<Text/> element does not properly occlude

### ISSUE THREAD

**Issue by felipecocco** [facebook/react-vr#198]
We use GitHub Issues for bugs and support tracking for the preview

--- Please use this template, and delete everything above this line before submitting your issue ---

### Description

<Text/> element does not appear to properly occlude when positioned in 3D space; renders properly as child of <View/> component but not when styling is applied to it directly.

#### Expected behavior

<Text/> element placed behind <View/> planes in 3D should be occluded
### Reproduction
Example of what is rendered with the code next to it:
![image](https://cloud.githubusercontent.com/assets/4644625/26107175/60c26142-3a16-11e7-9949-581c2fa078a8.png)

Changing order of sibling elements also makes no difference.

### Solution

Making it a child of a view with the transformation solves the issue, but my understanding of the documentation suggests that it shouldn't be necessary?

### Additional Information

* React VR version: 1.1
* Operating System: MacOS
* Graphics Card: Intel HD Graphics 5000
* Browser: Chrome 58
* VR Device: Out of VR

**Comment by mikearmstrong001** [comment]
Thanks for the report.

It looks like this element is missing out of setting `renderGroup: true` on the style when a transform  has been specified.

The reason for this is that in most part we try to careful render the order based on hierarchy and this is to avoid z fighting issues. The exception is when `renderGroup: true` is specified on the style or when a transform is applied.

Wrapping the text in a view which carries the transform would be a work around.

**Comment by mikearmstrong001** [comment]
fixed
