### ISSUE TITLE
OBJ attempted to load unknown material

### ISSUE THREAD

**Issue by justinireland** [facebook/react-vr#201]
I'm getting this error when trying to use materials with my objects:

`OBJ attempted to load unknown material: Velvet.2.2.3`

Searching for this error hasn't returned any useful info. Initially I thought it might be a problem with my mtl file but when I test with the creature material used in one of the examples I get the same error.

* React VR version: v1.1.0
* Operating System: MacOS
* Graphics Card: AMD Radeon R9 M370X
* Browser: Chrome
* VR Device: No HMD

**Comment by andrewimm** [comment]
Could you provide some code that reproduces this error?

When you use OBJ files, you need to reference both the OBJ (contains the geometry) and the MTL file (contains the coloring / texturing info for different named materials).

This particular error means that your OBJ file is referencing a material named "Velvet.2.2.3" that is not contained within your MTL file.

**Comment by justinireland** [comment]
Ok, pardon my ignorance. I think the problem is that the object is not correctly referencing the material.
