### ISSUE TITLE
CLI: `'yarn' is not recognized as ...` message for operations on Windows

### ISSUE THREAD

**Issue by FLGMwt** [facebook/react-vr#203]
### Description

Bug:

The [packager check](https://github.com/facebook/react-vr/blob/master/react-vr-cli/src/getPackager.js#L20) on Windows, in contrast to the same check on non-Windows platforms, does not mute error output. Consequently, the following message is output when running `yarn --version`:

```
'yarn' is not recognized as an internal or external command,
operable program or batch file.
```

Since `npm` is a legitimate and supported fallback, I believe this adds noise to the output and, more concerningly, confusion for developers not aware of yarn.

#### Expected behavior

In the absence of `yarn` on Windows, `react-vr` should not report a `yarn` error.

#### Actual behavior

The following message appears on all `react-vr-cli` output on Windows: 

```
'yarn' is not recognized as an internal or external command,
operable program or batch file.
```

### Reproduction

On a Windows system, without the `yarn` packager installed or available on the current path, run `react-vr` with no parameters. You should see the "'yarn' is not recognized" error.

### Solution

Mute output for the `yarn` check on Windows: `yarn --version 2> NUL` (PR coming up shortly)

### Additional Information

* React VR version: react-vr-cli: "3.3.0"
* Operating System: Windows 10
* Graphics Card: N/A
* Browser: N/A
* VR Device: N/A

**Comment by mikearmstrong001** [comment]
thank you!

**Comment by mikearmstrong001** [comment]
I'm going to close this issue now the PR is available
