### ISSUE TITLE
Model rendering with .obj and .mtl texture rendering issue

### ISSUE THREAD

**Issue by ArseniyKotov** [facebook/react-vr#208]
### Description

When trying to render a model with an .obj and .mtl file, the model's textures do not render correctly. I could totally be misunderstanding the issue here but ive tried this with two other models and am getting the same issue.

The .mtl file doesn't have any other file dependencies.

#### Expected behavior

Model's texture should render

#### Actual behavior

Model has a general black color instead of its textures

### Reproduction

Ive attached the model zip to this post as well as screenshots of the render method used to display this model and its result.

### Solution

Not sure.

### Additional Information

* React VR version: react-vr: 1.1.0 react-vr-web: 1.1.0
* Operating System: OSX
* Graphics Card: Radeon Pro 450 with 2GB memory
* Browser: Chrome 58.0.3029.110 (64-bit)
* VR Device:  N/A

[dvfpebi281kw-Cyborg.zip](https://github.com/facebook/react-vr/files/1032345/dvfpebi281kw-Cyborg.zip)

<img width="808" alt="screen shot 2017-05-26 at 8 40 52 am" src="https://cloud.githubusercontent.com/assets/25472327/26501816/81e428c0-41ef-11e7-8a7a-b21c3ec345d5.png">
<img width="924" alt="screen shot 2017-05-26 at 8 44 29 am" src="https://cloud.githubusercontent.com/assets/25472327/26501833/8f10f410-41ef-11e7-9e78-8d1cf1e787cb.png">

**Comment by mikearmstrong001** [comment]
Thanks for sharing the example, this helps us help you!

The mtl file doesn't have any textures assigned. Inline is you mtl and then following that is an example from our tests. As you can see your file is missing the `map_kd` entry which references the texture, also when I inspect the mesh there are no entries for texture coordinates and this suggests that there are options missed during the export process.

I'll close this issue but feel free to comment if you need a little more help.

```
# Blender MTL File: 'Drone Mesh.blend'
# Material Count: 3

newmtl Material
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.061264 0.061264 0.061264
Ks 0.500000 0.500000 0.500000
Ni 1.000000
d 1.000000
illum 2

newmtl Material.001
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.000000 0.292506 0.640000
Ks 0.500000 0.500000 0.500000
Ni 1.000000
d 1.000000
illum 2

newmtl Material.002
Ns 96.078431
Ka 0.000000 0.000000 0.000000
Kd 0.640000 0.640000 0.640000
Ks 0.500000 0.500000 0.500000
Ni 1.000000
d 1.000000
illum 2
```

```
# Max2Mtl Version 4.0 Mar 10th, 2001
#
# Multi/Sub Creature (3) to come
#
newmtl Body
map_kd Crea2.jpg
Ka  0.4 0.4 0.2
Kd  0.4 0.4 0.2
Ks  0.9 0.9 0.9
d  1.0
Ns  1.0
illum 2
```
