### ISSUE TITLE
Unable to publish my project (Building a production release )

### ISSUE THREAD

**Issue by Shikhar447** [facebook/react-vr#211]
We use GitHub Issues for bugs and support tracking for the preview
I was trying to do `npm run bundle` , it gave me errors, also I'm using latest node.js and npm version
the stacktrace is:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files (x86)\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'bundle' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 verbose run-script [ 'prebundle', 'bundle', 'postbundle' ]
5 info lifecycle ReactVr@0.0.1~prebundle: ReactVr@0.0.1
6 silly lifecycle ReactVr@0.0.1~prebundle: no script for prebundle, continuing
7 info lifecycle ReactVr@0.0.1~bundle: ReactVr@0.0.1
8 verbose lifecycle ReactVr@0.0.1~bundle: unsafe-perm in lifecycle true
9 verbose lifecycle ReactVr@0.0.1~bundle: PATH: C:\Program Files (x86)\nodejs\node_modules\npm\bin\node-gyp-bin;C:\ReactVr\ReactVr\node_modules\.bin;C:\oraclexe\app\oracle\product\10.2.0\server\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Java\jdk1.7.0_25\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Condusiv Technologies\ExpressCache\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\nodejs\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\Java\jdk1.7.0_25\bin;C:\Program Files\MongoDB\Server\3.2\bin;C:\Users\acer\AppData\Local\atom\bin;C:\Users\acer\AppData\Local\Microsoft\WindowsApps;E:\apache-maven-3.3.9\bin;C:\Users\acer\AppData\Roaming\npm
10 verbose lifecycle ReactVr@0.0.1~bundle: CWD: C:\ReactVr\ReactVr
11 silly lifecycle ReactVr@0.0.1~bundle: Args: [ '/d /s /c', 'node node_modules/react-vr/scripts/bundle.js' ]
12 silly lifecycle ReactVr@0.0.1~bundle: Returned: code: 1  signal: null
13 info lifecycle ReactVr@0.0.1~bundle: Failed to exec bundle script
14 verbose stack Error: ReactVr@0.0.1 bundle: `node node_modules/react-vr/scripts/bundle.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files (x86)\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ReactVr@0.0.1
16 verbose cwd C:\ReactVr\ReactVr
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "bundle"
19 error node v6.10.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error ReactVr@0.0.1 bundle: `node node_modules/react-vr/scripts/bundle.js`
22 error Exit status 1
23 error Failed at the ReactVr@0.0.1 bundle script 'node node_modules/react-vr/scripts/bundle.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ReactVr package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node node_modules/react-vr/scripts/bundle.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ReactVr
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ReactVr
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]`

 
--- Please use this template, and delete everything above this line before submitting your issue ---

### Description

[FILL THIS OUT: Bug or Feature Request? For a Bug please explain what you did, what you expected to happen, and what actually happens. Sections below]

### Reproduction

[FILL THIS OUT: Try to reproduce your bug in a minimal example, maybe you could alter one of the samples to demonstrate the problem]

### Solution

[FILL THIS OUT: What needs to be done to address this issue? Ideally, provide source code or a patch with a fix.]

### Additional Information

* React VR version: react-vr
* Operating System: Windows 10
* Graphics Card: Intel
* Browser: Chrome
* VR Device: NO

**Comment by mikearmstrong001** [comment]
I'm having a problem recreating this on both Windows and Mac and the log above is fairly difficult to follow because of the layout.
Would you mind reporting the definite version numbers of npm and yarn as well as attaching a `npm ls` and build log as file attachments.
Thanks

**Comment by Shikhar447** [comment]
npm version: 3.10.10
yarn version: 0.24.5

I have attached a `npm ls` and build log file in this zip file:
[ReactVr.zip](https://github.com/facebook/react-vr/files/1038308/ReactVr.zip)

**Comment by MrKanthaliya** [comment]
Even I got same issue.

E:\React\Sieben>npm run bundle

> Sieben@0.0.1 bundle E:\React\Sieben
> node node_modules/react-vr/scripts/bundle.js

Loading dependency graph, done.
Loading dependency graph, done.
WARN: Output exceeds 32000 characters
bundle: start
bundle: finish
bundle: Writing bundle output to: E:\React\Sieben\vr\build\index.bundle.js
bundle: Done writing bundle output
bundle: start
bundle: finish
bundle: Writing bundle output to: E:\React\Sieben\vr\build\client.bundle.js

bundle: Done writing bundle output
fs.js:641
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: UNKNOWN: unknown error, open 'C:\Users\<user>\.babel.json'
    at Error (native)
    at Object.fs.openSync (fs.js:641:18)
    at Object.fs.writeFileSync (fs.js:1347:33)
    at process.save (E:\React\Sieben\node_modules\babel-register\lib\cache.
js:48:16)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
An error occurred during the bundling process. Exited with code 1.
Look at the packager output above to see what went wrong.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Sieben@0.0.1 bundle: `node node_modules/react-vr/scripts/bundle.js
`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Sieben@0.0.1 bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<user>\AppData\Roaming\npm-cache\_logs\2017-05-30T13_58_2
7_068Z-debug.log

**Comment by mikearmstrong001** [comment]
This sounds similar to this https://github.com/facebook/react-native/issues/11803

Would you mind testing by changing bundle.js which can be found at

https://github.com/facebook/react-vr/blob/a284d2b8e27b039154586fbe4aa6fab9ad930e83/scripts/bundle.js#L35

from:
```
{stdio: 'inherit', cwd: root}
```
to:
```
{stdio: 'inherit', cwd: root, shell: true, env : {'BABEL_DISABLE_CACHE': '1'}}
```
