### ISSUE TITLE
Oculus browser access to microphone 

### ISSUE THREAD

**Issue by ArseniyKotov** [facebook/react-vr#215]
### Description

Currently when running an application in the default gear vr browser, there is no way for the system to access the phone's microphone for input.

### Additional Information

* React VR version: latest versions for both react vr 
* Operating system: android 
* Browser: DEFAULT GEAR VR 
* VR device: Gear VR

**Comment by andrewimm** [comment]
Thanks for your input. This repository is for the React VR library, and isn't actually associated with Oculus Browser in any way. However, I will convey this information to the team and see if they are working on providing permissions for the microphone.

**Comment by ArseniyKotov** [comment]
I am very sorry for the misunderstanding. Thank you very much. Do you want me to close this post?
