### ISSUE TITLE
Text Flow

### ISSUE THREAD

**Issue by nikgraf** [facebook/react-vr#216]
### Description

The documentation states:

> Text container: all the text flows as if it was one

#### Expected behavior

The amount of text components should not change the rendering behaviour.

#### Actual behavior

<img width="1032" alt="screen shot 2017-06-04 at 09 12 03" src="https://cloud.githubusercontent.com/assets/223045/26759709/78a87bbc-4906-11e7-8c40-4622b0e7e5bb.png">
<img width="1060" alt="screen shot 2017-06-04 at 09 12 19" src="https://cloud.githubusercontent.com/assets/223045/26759710/7b584e00-4906-11e7-86ae-4fa41e850103.png">

### Reproduction

```jsx
        <Text
          style={{
            color: 'lightblue',
            backgroundColor: '#335',
            fontWeight: 400,
            fontSize: 0.2,
            layoutOrigin: [0.5, 0.5],
            padding: 0.2,
            textAlign: 'center',
            textAlignVertical: 'center',
            transform: [{ translate: [0, 0, -1] }]
          }}
        >
          hello world
        </Text>
```

vs

```jsx
        <Text
          style={{
            color: 'lightblue',
            backgroundColor: '#335',
            fontWeight: 400,
            fontSize: 0.2,
            layoutOrigin: [0.5, 0.5],
            padding: 0.2,
            textAlign: 'center',
            textAlignVertical: 'center',
            transform: [{ translate: [0, 0, -1] }]
          }}
        >
          <Text>hello world</Text>
        </Text>
```

### Additional Information

* React VR version: 1.1.0
* Operating System: MacOS
* Graphics Card: Intel
* Browser: Chrome
* VR Device: Out of VR

**Comment by mikearmstrong001** [comment]
This is due to incorrect handling of when the outer text is empty. Fix incoming

**Comment by mikearmstrong001** [comment]
fixed

**Comment by nikgraf** [comment]
@mikearmstrong001 cool thx, are you going to cut a new release soon?

**Comment by nikgraf** [comment]
@mikearmstrong001 I also noticed when I do `paddingLeft` and `textAlign: 'left'` the Text itself is left-aligned. Is this a bug or a feature?
