### ISSUE TITLE
Added font set instance code is incorrect

### ISSUE THREAD

**Issue by 37372842** [facebook/react-vr#221]
fonts.md文件加载字体集 实例代码有误。遍历fallbackFonts的时候调用的方法里面只有一个参数，在该方法中却多了两个参数。
<img width="893" alt="qq20170608-200958 2x" src="https://user-images.githubusercontent.com/18411315/26928122-5ec37092-4c87-11e7-8523-cdf308b0345d.png">
这是我的代码：
<img width="1079" alt="qq20170608-202047 2x" src="https://user-images.githubusercontent.com/18411315/26928254-069878d0-4c88-11e7-9fe1-8e2d0d7f7841.png">

**Comment by andrewimm** [comment]
Updated docs.
