### ISSUE TITLE
could you please advice is there a possibility to access the  phone's microphone using ReactVR for input?

### ISSUE THREAD

**Issue by marwajawad** [facebook/react-vr#222]
We use GitHub Issues for bugs and feature requests

--- Delete everything above this line before submitting your issue ---

### Description

Is this a Bug or a Feature Request?
For a Bug please explain below what you did, what you expected to happen, and what actually happens.

### Reproduction

List all the steps required to encounter the issue you're reporting. These steps should be clear and concise.

An example of your code that reliably reproduces the issue is ideal.

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* 'react-vr' package version: [FILL THIS OUT: get this by running `npm list react-vr`]
* 'react-vr-web' package version: [FILL THIS OUT: get this by running `npm list react-vr-web`]
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?]
* Graphics Card: [FILL THIS OUT: NVIDA, ATI, Intel? Which Driver?]
* Browser: [FILL THIS OUT: Oculus Browser, Chrome, Edge, Safari? Which version?]
* VR Device: [FILL THIS OUT: In or Out of VR? Headset? ]

**Comment by andrewimm** [comment]
React VR is just JS running in the browser, so you can access the microphone the same way you would in any JS app. Since `navigator.mediaDevices` is only available in the main user window and not web workers, you'd need to implement it in `client.js` or a Native Module.

Within your setup in client.js, you can write the following:

```
navigator
  .mediaDevices
  .getUserMedia({audio: true})
  .then(stream => {
    // use the MediaStream from the microphone in some way
  })
  .catch(err => {
    // handle error
  });

```

**Comment by marwajawad** [comment]
@andrewimm Thank you so much for your feedback, I tried to enable the Mic and it worked... actually I'm now a little bit confused on the syntax to  use the normal JS libraries, I am trying to use the WebKitSpeechRecognition, to take voice commands as an input and it didn't work .. below is the code that I have written in the client.js file, could you please check it and let me know if I am missing anything?

  navigator
  .mediaDevices
  .getUserMedia({audio: true})
  .then(stream => {
    //console.log(stream);
    // use the MediaStream from the microphone in some way
  })
  .catch(err => {
    // handle error
  });
  var recognition = new webkitSpeechRecognition();
 	recognition.lang="en-us";
  recognition.onresult=(event => {
    var text = "";
    for (var i = event.resultIndex; i < event.results.length; ++i) {
        text+=event.resultIndex[i][0].transcript;
    }
    console.log(text);
  });
  recognition.start();

**Comment by andrewimm** [comment]
@marwajawad you can either add a script into client.js by installing an npm module and `import`-ing or `require()`-ing it, or you can add a new script to your index.html file like you mention above.

Issues on this github repository are reserved for dealing with bugs or feature requests related to React VR, so I can't help you further here. Your questions seem to be more generically related to web development, so I'd recommend taking them to someplace like Stackoverflow if you get stuck.
