### ISSUE TITLE
iOS opens its own player for videos

### ISSUE THREAD

**Issue by leocavalcante** [facebook/react-vr#228]
I've made a little webapp to display 360 videos using `VideoPane` works nice on desktops and Androids. The problem is on iOS, when I hit play it starts the video on it own player instead of using the `VideoPane`. How to solve this?

**Comment by andrewimm** [comment]
Can you provide more specifics? Code? Video of the behavior you're describing? Thanks!

**Comment by leocavalcante** [comment]
Dup: https://github.com/facebook/react-vr/issues/196
Sorry
