### ISSUE TITLE
How to dynamically generate Components in React-VR?

### ISSUE THREAD

**Issue by MrKanthaliya** [facebook/react-vr#229]
```
render(){
return(
{this.state.data.map((number,i) =>
        <ListItem key={i}
                  value={number.component} />
      )}
)
}
```

The above code does not work with react-vr which works with ReactJs. Is there any support for it? how else we can dynamically generate components.

**Comment by RangerMauve** [comment]
Components need to return single JSX elements, not arrays. Try wrapping them in a View
