### ISSUE TITLE
Easing can only be imported from React Native

### ISSUE THREAD

**Issue by michaelmang** [facebook/react-vr#236]
### Description

I attempted to import _Easing_ which is specified as a React VR API like so:

~~~
import {
  Text,
  View,
  Animated,
  Easing
} from 'react-vr';
~~~

#### Expected behavior
Since Text, View, and Image are found in React Native and React VR but imported from _react_vr_, one would expect to be able to import _Easing_ from react-vr.

#### Actual behavior
Easing came up as undefined when importing from react-vr.

### Solution

The only solution was to import Easing from _react_native_:

`import { Easing } from 'react-native';`

**Comment by andrewimm** [comment]
The versions of Text, View, Animated, etc that we provide on React VR are different from their React Native implementations. For things like Easing that are the same in RN, we don't proxy them over to the react-vr package. I'd classify this as expected behavior.

**Comment by xixixao** [comment]
The problem is this is never mentioned anywhere, so it is quite confusing, because the docs do not distinguish between `Animated` and `Easing` (they are both in API section). Should there be `React VR APIs` and `APIs` sections, each documented with the correct way to use the modules?
