### ISSUE TITLE
How to use materialParameters with THREE.js

### ISSUE THREAD

**Issue by JosephMoralesGE** [facebook/react-vr#238]
I noticed in the REACT VR docs regarding the materialParameters prop for the Model component it says the following:

set material parameters in three.js

...
I know what three.js is, but im not sure how to use it within this prop, materialParamaters. Can someone show me an example of using three.js WITHIN this prop?

**Comment by mikearmstrong001** [comment]
Can I ask your use case to make sure I can give you the most relevant information?

Here's an example I'm using in a test to apply custom shaders to a plane.

```
const vertexShader = `
varying vec2 vUv;
varying vec4 vMVPosition;
uniform float parameter1;
void main( ) {
  vUv = uv;
  vMVPosition = modelViewMatrix * vec4(position * parameter1, 1.0);
  gl_Position = projectionMatrix * vMVPosition;
}
`;

const fragmentShader = `
uniform sampler2D texture;
varying vec2 vUv;
varying vec4 vMVPosition;
void main( void ) {
  gl_FragColor = texture2D(texture, vUv);
}

...

        <Plane
          dimWidth={this.state.width}
          dimHeight={this.state.width}
          style={{
            transform: [{translate: [-2, 0, -3]}, {rotateY: this.state.rotation}],
            color: this.state.colored ? '#4444ff' : '#ffffff',
          }}
          onInput={this._onInput}
          lit={this.state.lit}
          texture={this.state.textured ? require('../assets/sfskyline.jpg') : null}
          materialParameters={{
            uniforms: { "parameter1": { value: 1.0 } },
            vertexShader: vertexShader,
            fragmentShader: fragmentShader,
          }}
          wireframe={this.state.wireframe}
        />

`;

Models are less clear cut because they often have material definitions which stipulate how something should be rendered. It is likely we'll be removing this override from Models and I would be inclined to use gltf models which can contain their own shader

**Comment by ericseaton-avatar** [comment]
@mikearmstrong001 I followed your example and got some awesome shaders going - thanks for that! I'm having some issues animating uniform values. 

`<Box
  dimWidth={1}
  dimHeight={1}
  style={{
    transform: [
      {translate: [-2, 0, -2]},
      {rotateY: '20deg'}
    ],
    color: '#4444ff'
  }}
  lit={true}
  materialParameters={{
    uniforms: {
      'time': { value: seconds, hidden: 1 }
    },
    vertexShader: this.vertexShader,
    fragmentShader: this.fragmentShader,
  }}
/>`

The `seconds` above is just running an interval on mount and I can confirm the value is changing within my render but it doesn't update the object. Did I miss something or is this not supported?
