### ISSUE TITLE
Pano image resolution dropped on mobile device

### ISSUE THREAD

**Issue by hjnieuwenhuizen** [facebook/react-vr#239]
I am not sure if this is a bug or if there is a setting I need to adjust, but I added a Pano component and set the source to a photo capture with a Samsung Gear 360 (dimensions: 7776px X 3888px). On my PC the image quality is fine yet when i access the app via my photo the image quality is not good. Definitely a drop in resolution.

**Comment by mikearmstrong001** [comment]
Three.js will be automatically resizing the image to the maximum size that is supported by the browsers. If you inspect the console logs for the device you've see something like (I've used one of my large example equirects to test)

```
THREE.WebGLRenderer: image is too big (7088x3544). Resized to 4095x2047 <img crossorigin=​"Access-Control-Allow-Origin" src=​"assets/​pano.jpg">​
clampToMaxSize @ main.bundle:16046
```

My suggestion is to manually downsize the image to a maximum width of 4096 and use the best quality image down sizer available. The other suggestion is use the equirect2cubemap tool which you'll find in the tools folder and convert to cubemap

Hope this helps

**Comment by hjnieuwenhuizen** [comment]
Ok cool. Thank you.
