### ISSUE TITLE
AmbientLight & SpotLight

### ISSUE THREAD

**Issue by hjnieuwenhuizen** [facebook/react-vr#240]
I am struggling to get these components to work correctly. Does anyone have a basic example? 
Do i need to create a Native View?

**Comment by mikearmstrong001** [comment]
This is an example of the lights used in our test.

Can you explain or provide an example on what is not working.

```
/**
 * Copyright (c) 2016-present Oculus. All Rights Reserved.
 *
 * Simple example showing how to add a lights to a scene.
 *
 */
'use strict';

const ReactNative = require('ReactNative');
const React = require('React');
const NativeModules = require('NativeModules');
const View = require('View');
const Image = require('Image');
const AppRegistry = require('AppRegistry');
const Pano = require('Pano');
const AmbientLight = require('AmbientLight');
const PointLight = require('PointLight');
const DirectionalLight = require('DirectionalLight');
const SpotLight = require('SpotLight');
const VrButton = require('VrButton');
const Model = require('Model');
const Text = require('Text');

class TestMeshLight extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      rotate: 0,
      lightType: 0,
    };
  }
  _nextLight() {
    this.setState({lightType:this.state.lightType+1});
  }
  _update() {
    this.setState({rotate:this.state.rotate+1});
    this.timer = requestAnimationFrame(()=>this._update());
  }
  componentWillMount() {
    this.timer = requestAnimationFrame(()=>this._update());
  }
  componentWillUnmount() {
    cancelAnimationFrame(this.timer);
  }
  render() {
    var text=['Ambient', 'Point', 'Directional', 'Spotlight'];
    return (
      <View
        style={{
          transform:[{translate: [0, 0, -5]}], layoutOrigin: [0.5, 0.5, 0],
          position:'absolute', alignItems: 'center',
        }}>
        <Pano source={require('../assets/chess-world.jpg')}/>
        <Text>
          {text[this.state.lightType%4]}
        </Text>
        {(this.state.lightType%4)===0 && <AmbientLight/>}
        {(this.state.lightType%4)===1 && (<PointLight style={{color:'red', transform:[{translate:[0,10,-5]}]}}/>)}
        {(this.state.lightType%4)===2 && (<DirectionalLight style={{color:'green'}}/>)}
        {(this.state.lightType%4)===3 && (<SpotLight style={{color:'blue', transform:[{translate:[0,10,-5]}]}} angle={60}/>)}
        <VrButton onClick={()=>this._nextLight()}>
          <Model
            style={{transform:[{scale:[0.5,1,1]}, {rotateX:this.state.rotate},{rotateY:this.state.rotate},{translate:[0,0,-1]}]}}
            lit={true}
            source={{
              obj: require('../assets/cube.obj'),
              mtl: require('../assets/cube.mtl'),
            }}
          />
        </VrButton>
      </View>
    );
  }
};

AppRegistry.registerComponent('test_meshlight', () => TestMeshLight);
```

**Comment by hjnieuwenhuizen** [comment]
Thank you Mike. I have added some of these light components yet I am not getting any kind of shadowing on my box and model components. Is this due to positioning of the lights? 

      <View>
        <AmbientLight/>
        <PointLight style={{color:'red', transform:[{translate:[0,10,-5]}]}}/>
        <DirectionalLight style={{color:'green'}}/>
        <SpotLight style={{color:'blue', transform:[{translate:[0,10,-5]}]}} angle={60}/>
        <Pano source={asset(this.state.view)}/>
        <Model
          source={{obj: asset('marker.obj')}}
          onInput={e => this.handleMarkerClick(e)}
          onEnter={e => this.handleMarkerHover(e)}
          onExit={e => this.handleMarkerExit(e)}
          style={{
              transform: [
                {translate: [100, -17, 100]},
                {scale: 0.1},
                {rotateX: 270}
              ],
              color: this.state.markerColor
          }}
        />
        <Box
          dimWidth={4}
          dimDepth={0.5}
          dimHeight={2}
          onEnter={e => this.handleBeaconHover(e)}
          onInput={e => this.handleBeaconClick(e)}
          style={{
              transform: [
                {translate: [10, 0, 10]},
                {rotateX: 30}
              ],
              color: '#ff4c4c',
              opacity: this.state.displayBillboard
          }}
        />
        <Text
          style={{
              transform: [
                {translate: [0.85, 0.1, 1]},
                {rotateY: 180},
                {rotateX: -30}
              ],
              fontSize: 0.08
          }}
          onEnter={e => this.handleBeaconHover(e)}
          onInput={e => this.handleBeaconClick(e)}
        >
          LaFamiglia
        </Text>
      </View>

**Comment by mikearmstrong001** [comment]
The key not working aspect is shadowing. As we've generally aimed for 360 media and framerate we've avoided exposing this property. I'll make a note to add but will default to disabled

**Comment by hjnieuwenhuizen** [comment]
Cool. Thank you for confirming.

**Comment by hjnieuwenhuizen** [comment]
Sorry, could you please confirm if the includes shading on mesh components. What does the DirectionalLight component currently do?

**Comment by mikearmstrong001** [comment]
This includes meshes that have been marked as lit={true}

A directionalLight is lighting that is in a particular direction and the position of the component has no affect on this
