### ISSUE TITLE
postMessage to Parent from click event

### ISSUE THREAD

**Issue by hjnieuwenhuizen** [facebook/react-vr#241]
Struggling to get my app to post a message to its parent. Is there a special way to do this?

  handleMarkerClick(e) {
    let eventType = e.nativeEvent.inputEvent.eventType
    if(eventType === 'click' || eventType === 'touchstart') {
      let data = {}
      window.postMessage("I'm loaded","http://localhost:8080/", data);
    }
  }

Currently getting this error:

Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': The 2nd argument is neither an array, nor does it have indexed properties.

https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage

**Comment by mikearmstrong001** [comment]
React VR code runs on a webworker and this doesn't have access to window.

What you need to do is create a NativeModule which you send a message. As the native module runs on the main browser window loop this can then send the message.

https://github.com/facebook/react-vr/blob/master/docs/NativeModules.md

**Comment by hjnieuwenhuizen** [comment]
Makes sense. Thank you.
