### ISSUE TITLE
Instructions on how to use with React Native

### ISSUE THREAD

**Issue by dabit3** [facebook/react-vr#246]
### Description

From what I understand, this being built using React Native, it should work with React Native. Is there any documentation on how to do this?

If not, can you give me a quick idea how to get started, and I can submit a PR with this documentation? 

Thanks.

### Solution

Produce documentation / examples on how to use with React Native (if possible)

**Comment by andrewimm** [comment]
Please read the explanation on #225 

While it's built on React Native, that unfortunately doesn't make it easy to integrate with a React Native application. That would be equivalent to trying to make Android RN components work in an iOS RN app. Down the road, we'll hopefully have native runtimes for RVR, but there's a lot of work involved there.
