### ISSUE TITLE
cannot rotate or move initially in chrome web, have to entervr then exitvr before you can use web controls

### ISSUE THREAD

**Issue by copypasteearth** [facebook/react-vr#247]
hello, I'm running the example and I cannot pan around initially in chrome, I have to entervr then exitvr before I'm able to use controls in web. I opened edge and I can pan around initially in web but in chrome I have to entervr then exitvr before I can pan around with just the webbrowser. I'm using the latest version of chrome, windows 10

**Comment by mikearmstrong001** [comment]
Can you check if you have the webvr emulation plugin for chrome running, if so try disabling and report back.

**Comment by copypasteearth** [comment]
yes, that worked, I disabled the plugin and it worked as expected
