### ISSUE TITLE
resources for RCTVideoModule?

### ISSUE THREAD

**Issue by hartbeatnt** [facebook/react-vr#25]
### Description

I am trying to get a 360 video to play in react-vr. There is nothing about this in the docs, but poking through the React-vr-web folder I found the RCTVideoModule file, which seems designed to handle this. Are there any resources you can point me towards in terns of getting this running?

Thank you,
Nate

**Comment by andrewimm** [comment]
We're still working on the dependencies that help that module render properly, so unfortunately videos aren't support at this time. Sorry!

**Comment by hartbeatnt** [comment]
Ok, thank you. Is the same true for the RCTAudioModule?

Thanks,
Nate

**Comment by andrewimm** [comment]
RCTAudioModule should work. The dependent module, `ovr-audio` has been published to npm, and I believe it's possible to build experiences with full positional, binaural audio. I'll try to put together a demo showing how to use it this weekend, if I can find the time. Hopefully we can have more thorough documentation of the supported NativeModules in the next week, there's some cool abilities in there.

**Comment by philipp-az** [comment]
Hope you can add support for 3d 360 videos as well as stereoscopic video planes soon.

**Comment by ufon** [comment]
look forward to the opportunity to add 360 videos. pls!

**Comment by DilipRamirez** [comment]
@andrewimm  would you mind sharing the basics on how to use the AudioModule? i'm having a very hard time trying to reverse-engineer the code! (just starting out with the framework)

**Comment by anthonybarsotti** [comment]
I was diving into the source of the Pano component and noticed it's easy enough to get 360 video working by applying the THREE.VideoTexture to the sphere's material. Are there any issues with this approach?

**Comment by johnnyshankman** [comment]
@amberroy any updates on plans for this? I'd love to do some 360 video with the `Pano` component.

**Comment by ufon** [comment]
+1

**Comment by amberroy** [comment]
Yesterday's update to npm packages adds a `<Video>` component for 2D video.  Support for 360 video is also planned.

**Comment by Eduardo10edu** [comment]
Me coloca em vídeos adultos de novinhas adolescentes

**Comment by mikearmstrong001** [comment]
`<VideoPano>` is now available as a component

examples of `<Video>` and `<VideoPanel>` can be found at https://github.com/facebook/react-vr/tree/master/Examples

**Comment by Jackson-Yin** [comment]
I want to play 3d video with react-vr.  Video is  a component for displaying 2D video.  VideoPano is a component for displaying 360 video. How can I play one 3d video with react-vr?
