### ISSUE TITLE
unable to enter VR mode, after pressing back button to exit VR mode - GearVR

### ISSUE THREAD

**Issue by brianyang** [facebook/react-vr#253]
### Description
when in VR mode on gear VR headset 2017, pressing the back button doesn't seem to exit VR mode properly

Bug
* pressing back button in gear VR, when in VR mode, causes the 'enter VR mode' to break

#### Expected behavior
* expected to go back to browser, and be able to choose to enter VR mode again

#### Actual behavior
* pressing back button, causes the 'enter VR mode' button to stop working

### Reproduction
* pressing back button in gear VR, when in VR mode, causes the 'enter VR mode' to break
- expected to go back to browser, and be able to choose to enter VR mode again
- pressing back button, causes the 'enter VR mode' button to stop working
- have to restart the phone to get the 'enter VR mode' button working again

### Additional Information

* 'react-vr' package version: [FILL THIS OUT: get this by running `npm list react-vr`]
* 'react-vr-web' package version: [FILL THIS OUT: get this by running `npm list react-vr-web`]
* Operating System: [MacOS]
* Graphics Card: [unknown]
* Browser: [Oculus Browser]
* VR Device: [Samsung Gear VR 2017 ]

**Comment by brianyang** [comment]
instead of pressing the back button, press the home button. then when returning to the browser, it seems to allow me to enter vr mode again.

**Comment by andrewimm** [comment]
Hmm, this used to work as intended. Will try to pinpoint whether it's a change in browser events or oversight in our framework.

**Comment by amitrajput1992** [comment]
@andrewimm Can you confirm if this is an issue with the react-vr package. I'm able to reproduce this on OnePlus 3 with WebVR enabled.

---
Additional Information 

- react-vr' package version: 1.0.3
- 'react-vr-web' package version: 1.0.3
- Operating System: Linux mint
- Graphics Card: [unknown]
- Browser: chrome 59.0.3071.109, chromium 58.0.3029.110
- VR Device: [none]

**Comment by copypasteearth** [comment]
I have the same issue with chrome using cardboard too

**Comment by breadadams** [comment]
If I may ask, @copypasteearth, what device are you using to run `react-vr` on google cardboard? Thanks!

**Comment by marcelosuzumura** [comment]
> I have the same issue with chrome using cardboard too
Me too, unfortunately.
I'm using Chrome 61.0.3163.98 on Android 5.0.2 and React VR 1.4.0

**Comment by copypasteearth** [comment]
@breadadams i was using samsung galaxy s4

**Comment by brianyang** [comment]
has this issue been resolved with this commit? 
https://github.com/facebook/react-vr/commit/7b7910e5c058dda90af61a71fb5f4fcddc158d83
