### ISSUE TITLE
[Question] Enable loop for video

### ISSUE THREAD

**Issue by JoeMaesai** [facebook/react-vr#254]
How can I enable loop and onEnded?
I have following code. It does not start play video again.
constructor(props) {
  super(props);
  this.state = {
   playerState: new MediaPlayerState({
     autoPlay: true, muted: true, loop:true, onEnded: ()=>{ console.log('Ended Video')}
    })
  };
}

<Video
                style={{ width: 2, height: 1}}
                source={ asset('video.mp4', {format: 'mp4'}) }
                playerState={this.state.playerState}
 />
<VideoControl
                style={{width: 2, height: 0.1 }}
                playerState={this.state.playerState}
 />

**Comment by andrewimm** [comment]
The only valid construction options for `MediaPlayerState` are `autoPlay`, `muted`, and `volume`.


`loop` and `onEnded` are properties of `Video`. If you move those properties to your video tag, like

```js
<Video
  style={{ width: 2, height: 1}}
  source={ asset('video.mp4', {format: 'mp4'}) }
  playerState={this.state.playerState}
  loop={true}
  onEnded={() => { console.log('Ended Video') }}
/>
```
you'll see the intended behavior.

https://facebook.github.io/react-vr/docs/mediaplayerstate.html
https://facebook.github.io/react-vr/docs/video.html

**Comment by JoeMaesai** [comment]
Hi Andrew


Thank you very much for your time. You are really kind.


Best Regards
Maesai
