### ISSUE TITLE
Lacking vert swipe makes React VR unusable laying down

### ISSUE THREAD

**Issue by andelar** [facebook/react-vr#260]
### Description

I saw the feature request, but this is not a feature request - it's a show-stopping usability bug, unless I am missing something.

Try laying down on the bed watching a scene on an iPhone... You end up staring up into the sky or down into the floor with no way of getting out of that view. 

For many scenes that means an incomprehensible blue or white screen. Users then try swiping but "nothing happens" (because they are just rotating around the Y axes while still staring up in the blue sky or the white ceiling etc). Then they leave!

I made a short check today and over 80% that entered a scene while laying down left because of this and said variations of "it didn't work" or "unusable". Many people browse the Internet while resting, I suppose all of us included... Need to fix or cannot use the framework.

#### Expected behavior

Compare how a pano is displayed and navigated on facebook.com or youtube.com (swipe in both X and Y directions).

#### Actual behavior

Can only look straight up if laying down on your back holding the phone above your face, or straight down if laying down on your stomach with the phone resting on the surface below your face.

### Reproduction

Any base example

### Solution

Add Vertical swipe urgently

**Comment by andrewimm** [comment]
The fix for this was actually implemented 6 days ago in f4b4c898235490cad3428b956470dd06ad7d1d39

We will release a new version soon incorporating these changes.

**Comment by andelar** [comment]
Wow that's fantastic! :-) You guys are really doing something spectacular here. I have not been so excited over a new framework for many years. Hats off to the amazing team that has made this possible!

**Comment by amberroy** [comment]
Appreciate the compliment.  :) This feature is included in today's release:
https://github.com/facebook/react-vr/releases/tag/v1.4.0
