### ISSUE TITLE
[Feature request] Opacity for Pano

### ISSUE THREAD

**Issue by andelar** [facebook/react-vr#264]
### Description

Would be fantastic to have an opacity style for Pano, to make a smooth transitioning between two panos. Looks a bit ugly to flip to flip to black and then flip to next scene. Any work-around that comes to mind? Amazing framework!

**Comment by amberroy** [comment]
One option may be to set the Pano 'tintColor' style property:
```
<Pano source={asset('chess-world.jpg')} style={{tintColor: 'red'}}/>
```

**Comment by andelar** [comment]
Good idea, yes that's a start. Thank you! :-)

**Comment by andelar** [comment]
If you would consider it, I would propose to keep this open. The problem isn't solved.

On a bright sunny day moving from position A to position B, it becomes a horrible transition experience to fade to black/gray and back. (And you can't "tint" to white.)

The only way to make a smooth transition from one Pano to another, similar, location is with an opacity property on Pano.

**Comment by KhaledGabr** [comment]
I totally agree, opacity of panormas is an essential   feature to create smooth transition between hotspots.

**Comment by macarran** [comment]
@andelar, @KhaledGabr opacity support for Pano and VideoPano components was added in the most recent 2.0.0 release.

**Comment by robin-k-wilson** [comment]
@macarran Can you provide the proper syntax for using opacity for the Pano components?

Context: I am loading a low quality blurryPano before high quality fullPano for users on 3G. The transition ideally goes from load react-vr > default background > fade-in onLoad() blurryPano > in-parallel: fade-in onLoad() fullPano and fade-out blurryPano. Similar to the above requests.

Issues:
I'm unable to use 'opacity' property inside Pano components and receive the error:

> "Warning: Failed prop type: Invalid props.style key `opacity` supplied to `Pano`. Bad object" 

I've also attempted enclosing the Pano inside an Animated.View component that has an initial opacity: Animated.value(0) then onLoad(), opacity transitions to opacity: 1. The animation does not affect Pano. 

My React-VR version is 5.5.1. Thank you.
