### ISSUE TITLE
[Feature request] Animated.loop like in RN

### ISSUE THREAD

**Issue by andelar** [facebook/react-vr#265]
### Description

Would be great to have loop on Animated, like in React Native:
https://facebook.github.io/react-native/docs/animated.html#loop

For now doing this workaround, if it can help someone:

  startAnimation(){
      Animated.sequence([
        Animated.timing(
         ...
        ),
        Animated.timing(
         ...
        )
      ])
    .start(() => {
      this.startAnimation();
    });
  }

**Comment by amberroy** [comment]
Thank for this suggestion and for sharing your workaround!

**Comment by mikearmstrong001** [comment]
We've recently update RN but we didn't pull in the latest Animated features to our patches.

**Comment by mikearmstrong001** [comment]
This is now resolved in GitHub master
