### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by githubrasmus354** [facebook/react-vr#267]
Page ReactVRConstants https://facebook.github.io/react-vr/docs/reactvrconstants.html not working.

**Comment by andrewimm** [comment]
The link works as expected; all of those docs are autogenerated from the code. The React VR Constants module doesn't export any methods, only constants, so there's nothing to generate: https://github.com/facebook/react-vr/blob/master/Libraries/VRModules/ReactVRConstants.js

If we add methods to it later, the docs will update to reflect that.
