### ISSUE TITLE
Generating Signed APK

### ISSUE THREAD

**Issue by hjnieuwenhuizen** [facebook/react-vr#270]
Hi guys, trust you are well :-). I have to advise that I came from a React background when starting with React-VR and have not really worked with React-Native much. I was hoping that you could provide a detailed tutorial how to generate the signed APK for my react-vr app as the andriod folder is missing from my app. Can i just copy what the create react native app generates? Also i have been wondering what will happen to my custom modules that i have created outside react-vr. Example using a iframe for a youtube vid. Will this all get bundled within the APK as well?

**Comment by mikearmstrong001** [comment]
There is no signed APK (which is Android) as while this framework uses React Native this is a web based framework. Creating a deployable set of JS script and assets which can be placed on a static webserver, there is no APK
