### ISSUE TITLE
How to Create a Multiple 360 Panorama Photos in react-vr?

### ISSUE THREAD

**Issue by Kumaresh-Rajalingam** [facebook/react-vr#271]
We use GitHub Issues for bugs and feature requests

--- Delete everything above this line before submitting your issue ---

### Description

Is this a Bug or a Feature Request?
For a Bug please explain below what you did, what you expected to happen, and what actually happens.

### Reproduction

List all the steps required to encounter the issue you're reporting. These steps should be clear and concise.

An example of your code that reliably reproduces the issue is ideal.

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* 'react-vr' package version: [FILL THIS OUT: get this by running `npm list react-vr`]
* 'react-vr-web' package version: [FILL THIS OUT: get this by running `npm list react-vr-web`]
* Operating System: [FILL THIS OUT: MacOS, Linux, or Windows?]
* Graphics Card: [FILL THIS OUT: NVIDA, ATI, Intel? Which Driver?]
* Browser: [FILL THIS OUT: Oculus Browser, Chrome, Edge, Safari? Which version?]
* VR Device: [FILL THIS OUT: In or Out of VR? Headset? ]

**Comment by amberroy** [comment]
Thanks for your question.  Please tell us more about the use case you're trying to support.

**Comment by Kumaresh-Rajalingam** [comment]
Hello amberroy I am trying to create VR tour using react-vr I do no that how to add multiple images

**Comment by mikearmstrong001** [comment]
You will want to set the pano source based on some state. Here is an example which changes the pano based on a button press

The key line is
```
<Pano source={this.state.source} />
```

```
/**
 * Copyright (c) 2016-present Oculus. All Rights Reserved.
 *
 *
 */
'use strict';

...

// Test both standard and cubemap pano.
class TestPano extends React.Component {
  constructor(props) {
    super(props);
    this.state = {source: {uri:'assets/chess-world_orient.jpg'}};
  }

  render() {
    return (
      <View
        style={{
          transform:[{translate: [0, 0, -3]}],
          layoutOrigin: [0.5, 0.5, 0], position:'absolute', alignItems: 'center',
        }}>
        <Pano source={this.state.source} />
        <VrButton
          style={{width:1, height:0.25, backgroundColor:'red'}}
          onClick={()=>this.setState({source: {uri:'assets/chess-world_orient.jpg'}})}
        >
          <Text style={{flex:1, fontSize:0.1, textAlign:'center', textAlignVertical:'center'}}>Equirect</Text>
        </VrButton>
         <VrButton
          style={{width:1, height:0.25, backgroundColor:'green'}}
          onClick={()=>this.setState({source: {uri:'assets/cube-world.jpg', stereo: 'TOP_BOTTOM_3D'}})}
        >
          <Text style={{flex:1, fontSize:0.1, textAlign:'center', textAlignVertical:'center'}}>Stereo Equirect</Text>
        </VrButton>
      </View>
    );
  }
};

AppRegistry.registerComponent('test_pano', () => TestPano);
```

**Comment by Kumaresh-Rajalingam** [comment]
Hello

Thanks for sharing this code

Please look at the following example link :
http://openspace.3dphy.com/?un=sa&ic=AshianaTheCenterCourtSF&md=t&map=t
I want to make same as like this it is possible in react vr? lemme know how
do this with floor plan and some icons with text

Thanks in advance

**Comment by amberroy** [comment]
Yes it is possible!  Have a look at our newest sample which is a virtual tour using linked 360 photos, similar to your example link.
`https://github.com/facebook/react-vr/tree/master/Examples/TourSample

**Comment by Kumaresh-Rajalingam** [comment]
Hello Amber Roy

Thanks for your response I am trying to build an real estate website i,e
real estate tour using react vr with floor plan and some animations I do no
that how to it responsible for all browsers? and mobile support

**Comment by andelar** [comment]
The tour example crashes on iPhone, same as I reported in #268 after about 15 clicks around the area.
https://github.com/facebook/react-vr/issues/268
(I compiled with the released 1.4.0, not by building react-vr for clarity.)

**Comment by yosun** [comment]
yeah please fix this crap on iOS

**Comment by andelar** [comment]
Yosun, Kumaresh, happy to let you know that you can do all those use cases in the tour framework (built with React VR) and also add own React VR components easily.
https://github.com/livetourlab/live-tour-lab

The earlier iOS issue in React VR 1.4.0 is solved in the React VR master branch, I verified it working. Happy to help if you need assistance to compile it.

If you like the framework, please star it and contribute! Cheers and enjoy!

**Comment by Kumaresh-Rajalingam** [comment]
can u please share some examples code with floor plan

https://livetour.istaging.com/57ecd104816dfa005668e914 like this

Thanks
