### ISSUE TITLE
[Question] Non-spatialized audio with Sound component?

### ISSUE THREAD

**Issue by mojenmojen** [facebook/react-vr#276]
Is there any way to play non-spatialized audio using the react-vr Sound component?

**Comment by amberroy** [comment]
Currently no, the audio will have the same position as the `<Sound>` component.

React VR does support non-spatialized audio with the VrSoundEffects API, see docs at:
https://facebook.github.io/react-vr/docs/vrsoundeffects.html

For example...
```
const ONE_SHOT_SOUND={uri: 'my-sound.wav'};
...
  componentWillMount() {
    VrSoundEffects.load(ONE_SHOT_SOUND);
  }
...
<VrButton
    onClick={() => {
      VrSoundEffects.play(ONE_SHOT_SOUND);
}}>
    <Text>CLICK to play</Text>
</VrButton>
```

**Comment by mojenmojen** [comment]
Thank you, that's very helpful. There are only a few methods listed in the documentation for this API. Are any other features like loop or pause supported?

**Comment by amberroy** [comment]
No those are the only features supported at this time.

**Comment by mojenmojen** [comment]
These features are needed for 2D audio elements such like background music and ambience. This is noted in the Oculus audio SDK docs here:

https://developer.oculus.com/documentation/audiosdk/latest/concepts/audio-intro-mixing/

Another missing feature is fade in and fade out for smooth audio transitions, both for 3D audio and 2D.

Could these features be added?

**Comment by mojenmojen** [comment]
If anyone happens upon this thread, I ended up using Howler as a native module. It has all of the 2D features you need, plus it also supports 3D spatial sound.

https://howlerjs.com/

**Comment by jgwinner** [comment]
Cool - does it move the sound in the <sound> nodes so that as you turn your head, you feel immersed?

HRTF's are really essential, even if it's a 'catch all' HRTF.

I noticed Howler has panningModel that will use HRTF's.

Did you have to write code to position all of the sound sources on each turn of the head?
