### ISSUE TITLE
 '__fbBatchedBridgeConfig is not set' error when importing external package code in vr/client.js

### ISSUE THREAD

**Issue by Kaizeras** [facebook/react-vr#277]
### Description
[BUG]

 I'm trying to import a class from an external package in `vr/client.js`, but I'm get the following error:
```
invariant.js:44 Uncaught Error: __fbBatchedBridgeConfig is not set, cannot invoke native modules
```

### Reproduction
1. Import a `asset` from  `react-vr` in `<project root>/vr/client.js`:
```
// Importing "asset"  crashes the app with the error given in the title
import {asset} from "react-vr";
function init(bundle, parent, options) {
    const vr = new VRInstance(bundle, 'WelcomeToVR', parent, {
        ...options,

//..
})
```

### Solution

I'm expecting to be able to add classes from an external library/package in `vr/client.js`

### Additional Information

* 'react-vr' package version: [`1.4.0`]
* 'react-vr-web' package version: [`1.2.0`]
* Operating System: (MacOS)

**Comment by copypasteearth** [comment]
I just had this same issue the other day but with something else. Im not 100% on this but try removing {} the brackets from {cnraycaster} in your import maybe

**Comment by copypasteearth** [comment]
I had this problem when i tried to import {asset} from 'react-vr';

**Comment by mikearmstrong001** [comment]
__fbBatchedBridgeConfig is related to a react vr js bundle and not the runtime. Would you be able to provide an repro that I can patch against the GitHub version as this ensure we are looking at the same thing.

**Comment by Kaizeras** [comment]
@mikearmstrong001 I don't think I fully understood what you're requesting. Can you provide a little bit more structure and context?

**Comment by mikearmstrong001** [comment]
@Kaizeras can you provide an repro of the problem that doesn't use modules I don't have access to eg `CnRayCaster`

**Comment by Kaizeras** [comment]
@mikearmstrong001 I've updated the example using @copypasteearth 's input on the issue.

**Comment by mikearmstrong001** [comment]
by importing 'react-vr' you also import 'react-native' and these are designed to run in the react vr webworker. It sounds like the Gaze implementation in your original example is another model designed to run in the React WebWorker.

React VR has two sides, 
- the runtime which handles (amongst others) the display and interaction events from the browse 
- the react code, this runs in a webworker and is used to describe the view hierarchy

This is not a bug.

It is possible to import modules in the client.js (runtime) for example it is possible to 
```
import * as THREE from 'three';
```

You do want to avoid importing anything related to react or react-native so if you do need to share a module between the two you will need to break part dependencies appropriately

**Comment by Kaizeras** [comment]
Thank you for the feeback, @mikearmstrong001 ! I'll look into my implementation and try to adjust it accordingly.

**Comment by jgwinner** [comment]
You asked for a sample that demonstrates the problem; I can provide this and also updated it at:

[https://github.com/facebook/react-vr/issues/401]

I just hope it's not a typo of mine :)
