### ISSUE TITLE
Using a CDN to serve bundled files (client.bundle.js and index.bundle.js)

### ISSUE THREAD

**Issue by amitrajput1992** [facebook/react-vr#279]
### Description

Is there a way to serve up the bundled files from a different server than where the application runs? 

For ex. after bundling both client.js and index.js I want to serve these files from `http://cdn.exp.com/***` to (take advantage of caching and other stuff) rather than to have these in the website directory. I see that inside VRInstance.js, the bundle(index.js) is always referenced from the working directory inside `bundleFromRoot` function. Though client.js bundle can be requested from external server. 
Since both of these are standalone bundles after building, it would be ideal that these can be referenced from any location, be it inside the app directory or on a different server.

I can set up a PR to address this issue if this wasn't on the roadmap for react-vr.

#### Expected behavior
Serving bundled files from a different source.

#### Actual behavior
VRInstance references bundled files always from the root directory.

### Solution
Add additional param for VRInstance options {bundleFromRoot: true/false} and corresponding test for this while referencing the bundles.

```
ReactVR.init(
    // When you're ready to deploy your app, update this line to point to
    // your compiled index.bundle.js
    'vr/index.vr.bundle?platform=vr&dev=true&enableHotReload=true',
    // Attach it to the body tag
    document.body,
    {
        bundleFromRoot: false 
    }
  );

this.rootView = createRootView(this.guiSys, root, {
      // Name of the mounted root module, from AppRegistry
      assetRoot: assetRoot,
      bundle: !options.bundleFromRoot? bundle: bundleFromRoot(bundle),
      customViews: options.customViews,
      enableHotReload: options.enableHotReload,
      initialProps: options.initialProps,
      isLowLatency: !this.player.isMobile,
      nativeModules: options.nativeModules,
    });
```

### Additional Information

* 'react-vr' package version: 1.3.0
* 'react-vr-web' package version: 1.3.0
* Operating System: Linux 
* Graphics Card: Intel HD 6000
* Browser: Chrome 59.0.3071.109, chromium 59.0.3071.109 
* VR Device: None

**Comment by mikearmstrong001** [comment]
So in short you want to be able to specify the absolute url. Rather than add another option perhaps detecting this in a renamed `bundleFromRoot` would be a better solution. PR would be much appreciated :)

**Comment by amitrajput1992** [comment]
I will setup a PR soon

**Comment by amitrajput1992** [comment]
sent #281 for this issue. @mikearmstrong001, please review.

**Comment by mikearmstrong001** [comment]
Many thanks I'll take a look

**Comment by mikearmstrong001** [comment]
closing and moving discussion to PR

**Comment by hitu4233** [comment]
Where we can get path of bundle.js and main.bundle.js in our local how we can put these on CDN and serve to our application?
