### ISSUE TITLE
Support stereo cubemaps with separate JPGs

### ISSUE THREAD

**Issue by iox** [facebook/react-vr#280]
I have looked at the Pano documentation and source code, and I have seen that **stereo** is only supported when the cubemaps or equirect images contain both images (left and right eye) in the same JPG, pasted together.

In our preexisting 360 content, we have independent cubemaps for each eye. For example `LEFT/cube/d.jpg` and `RIGHT/cube/d.jpg`. It is a huge amount of content, and if possible, we would like to reuse it as it is right now.

Ideally, it should be possible to declare a pano's source with separate JPGs or cubemaps for each eye. Example: 

```
pano_source = [
      {uri: 'LEFT/cube/r.jpg',     eye: 'left'},
      {uri: 'LEFT/cube/l.jpg',     eye: 'left'},
      {uri: 'LEFT/cube/u.jpg',     eye: 'left'},
      {uri: 'LEFT/cube/d.jpg',     eye: 'left'},
      {uri: 'LEFT/cube/f.jpg',     eye: 'left'},
      {uri: 'LEFT/cube/b.jpg',     eye: 'left'},
      {uri: 'RIGHT/cube/r.jpg',    eye: 'right'},
      {uri: 'RIGHT/cube/l.jpg',    eye: 'right'},
      {uri: 'RIGHT/cube/u.jpg',    eye: 'right'},
      {uri: 'RIGHT/cube/d.jpg',    eye: 'right'},
      {uri: 'RIGHT/cube/f.jpg',    eye: 'right'},
      {uri: 'RIGHT/cube/b.jpg',    eye: 'right'},
    ]

``` 

What do you think about this idea? Does it involve a major development effort?

Thank you very much.

**Comment by mikearmstrong001** [comment]
Your suggestion makes sense although I'd drop the eye property and just a list of 6 entries for mine cubemaps and 12 for stereo,with eye there are already nuances if there are > 6 entries for any one eye. A simple, ordered list is easy to explain

**Comment by MartinSherburn** [comment]
@iox, I have committed a change (8990e5c46898bcfd757ddc797fd192f39ccf243f) which will allow you to specify 12 independent cubemaps as requested. The format you should use is:

```
pano_source = [
      {uri: 'LEFT/cube/r.jpg'},
      {uri: 'LEFT/cube/l.jpg'},
      {uri: 'LEFT/cube/u.jpg'},
      {uri: 'LEFT/cube/d.jpg'},
      {uri: 'LEFT/cube/f.jpg'},
      {uri: 'LEFT/cube/b.jpg'},
      {uri: 'RIGHT/cube/r.jpg'},
      {uri: 'RIGHT/cube/l.jpg'},
      {uri: 'RIGHT/cube/u.jpg'},
      {uri: 'RIGHT/cube/d.jpg'},
      {uri: 'RIGHT/cube/f.jpg'},
      {uri: 'RIGHT/cube/b.jpg'},
    ]
```

The eye is implicit in the order, left comes first then right as per @mikearmstrong001's suggestion. Please let me know if you have any trouble with it.

**Comment by iox** [comment]
It's working nicely, thank you very much @MartinSherburn .
