### ISSUE TITLE
onLoadEnd on Pano not ready to display with rotation

### ISSUE THREAD

**Issue by andelar** [facebook/react-vr#282]
### Description

It's great to have the onLoadEnd callback when the Pano image is loaded given the big file sizes. Unfortunately, if displaying the Pano at that point, it briefly displays with 0 degrees rotation before the style transform rotateY kicks in, causing an ugly flicker.

If you look carefully at the official Tour example checked in the other day, you have the same issue. Each new view flickers in with 0 degree rotation, and then rotates. The sense of direction is lost in the process and it feels a bit unpleasant.

So right now I can think of no way to make a reasonable transition between two locations with React VR (!)

(The idea to fade to black, and then stay black while switching, is very ugly on bright scenes.)

### Reproduction

Official tour example

### Additional Information

* 'react-vr' package version: 1.4.0
* 'react-vr-web' package version: 1.4.0
* Operating System: MacOS
* Graphics Card: Intel
* Browser: Chrome
* VR Device: Out of VR

**Comment by mikearmstrong001** [comment]
The callback will happen the frame after the display and then when you set the rotation there is another another message from react to runtime - both runtime and react code runs async. The callback is meant to be informative rather than a sync point.

My suggestion is that you either fade in and out the new panos or use two panos, one the visible active one  and a second which is the next loading one with the state all ready to go. you swap when the second one completes the load. If you use keys on the components this helps the react code know which one has been removed.
https://facebook.github.io/react/docs/reconciliation.html#keys

**Comment by andelar** [comment]
Thank you for this, however how to fade between two panos? There is no opacity property and I cannot figure out a way to hide one. If displaying two they display in a jigsaw puzzle. So how to swap them in? I've struggled hard with this and cannot figure out any way to transition between two panos's without displaying the same rather ugly flicker as in the recent official tour example. Hope there is a way :-)

**Comment by andelar** [comment]
Is it possible with the current framework to do what you suggest? How to hide the second Pano?

_"use two panos, one the visible active one and a second which is the next loading one with the state all ready to go. you swap when the second one completes the load."_
=> How? How can you hide one of the two <Pano/> ? 
I tried the following wild ideas to hide one of them, but they all do nothing, still rendering a jigsaw puzzle, obviously a result of two visible <Pano/> at the same spot in space.
display={'none'}
opacity=0
I even tried scaling one panorama bigger than the other one, to not get the jigsaw puzzle, but if that is possible I can't figure out how to do it. I also resorted to madness like width=0 height=0 etc, but no effect.

How to hide the second Pano as you suggest?

**Comment by mikearmstrong001** [comment]
Here's an example of using a pair of Panos where one is displayed and the other is not. You were very close with your use of display :)

```
        <Pano key="urlofthispano" style={{display:'flex'}} source={this.state.source} />
        <Pano key="urlofthatpano" style={{display:'none'}} source={{uri: PISA_IMGS}} onLoad={() => console.log('loaded')}/>
```

I'm going to close this issue we can carry on the discussion on opacity/fade in the other issue.

**Comment by andelar** [comment]
YES working! Together with a small timer for the rotate to finish and with onLoadEnd instead of onLoad for it to work with cubemap sources also (not sure why). THANK YOU!!!! You guys rock!!!!
