### ISSUE TITLE
Gyroscope Option

### ISSUE THREAD

**Issue by hjnieuwenhuizen** [facebook/react-vr#285]
Is there an option to switch off gyroscope functionality? Where can i get a list of all the options that can be change when creating the VRInstance?

**Comment by larrylin28** [comment]
Do you mean the loading gyroscope or the compass? There's an option `hideCompass` for hiding compass. Not an option for hiding loading gyroscope. I think following may work:
```
const vr = new VRInstance(......);
vr.player.overlay.hideGyro();
```

Options are defined in `VRInstance.js` as flow type `VRInstanceOptions`

**Comment by hjnieuwenhuizen** [comment]
Thank you. I am talking about the functionality that uses a device gyroscope to pan around. I just want the touch panning. Imagine a user laying in bed trying to use my web app.
