### ISSUE TITLE
The files for browsers

### ISSUE THREAD

**Issue by extend1994** [facebook/react-vr#286]
Hi!
I am a member of CDNJS. There is a library request https://github.com/cdnjs/cdnjs/issues/11128 and I am the one in charge of adding this to our CDN. Though I read the README.md, https://facebook.github.io/react-vr/docs/getting-started.html#content and so on. I am still not sure which files should our CDN host. Could you please tell me if this library can be compatible with browsers and which files should we host? Thank you very much!

**Comment by andrewimm** [comment]
Thanks for the question. React VR isn't the type of library that can just be imported with a <script> tag. It can only be used as part of a larger compiled application, so it doesn't make sense to upload to a service like CDNJS.

**Comment by extend1994** [comment]
@andrewimm Thank you for the response!
