### ISSUE TITLE
Particle System Workflow

### ISSUE THREAD

**Issue by upressplay** [facebook/react-vr#297]
### Description
Tried getting aframe-react, aframe-particle-system-component and react-particles-js to work on my project. Caused a variety of dependency issues. What is everyone using? Any examples? 

#### Expected behavior
Add particle system to react VR environment. 

#### Actual behavior
Build failure

### Reproduction
Installed [aframe-react]( https://github.com/aframevr/aframe-react)
Installed [aframe-particle-system-component]( https://www.npmjs.com/package/aframe-particle-system-component)
Installed [react-particles-js]( https://www.npmjs.com/package/react-particles-js)

### Solution
A work flow that establishes particle effects in react-vr, without dependecy issues when calling npm install. 

### Additional Information
* 'react-vr' package version: 15.4.1
* 'react-vr-web' package version: 1.4.0
* Operating System: MacOS
* Graphics Card: AMD FirePro D300 2048 MB
* Browser: Chrome
* VR Device: Desktop testing

**Comment by mikearmstrong001** [comment]
If you wanted to create a particle system I'd suggest creating a native view that work alongside the three.js system.

**Comment by mikearmstrong001** [comment]
please reopen if required
