### ISSUE TITLE
Compatibility with React 16 beta?

### ISSUE THREAD

**Issue by kbrandwijk** [facebook/react-vr#300]
### Description
After upgrading to React 16 beta, I get the following error from all react-vr components:

>Unable to resolve module `react/lib/ReactPropTypes` from `[...]\node_modules\react-vr\Libraries\Components\View\View.vr.js`: Module does not exist

This is due to prop-types being moved to a seperate package. The warning for this has been there since React 15.5, so I would expect this to be taken care of.

#### Expected behavior
React-vr components should use prop-types package.

#### Actual behavior
Error.

### Reproduction

Run any react-vr project with these package versions:
```
react-dom: 16.0.0-beta.3,
react: 16.0.0-beta.3
```

### Additional Information

* 'react-vr' package version: 1.4.0 (latest)
* 'react-vr-web' package version: 1.4.0 (latest)
* Operating System: Windows

**Comment by andrewimm** [comment]
If you look at the master branch, you'll see that we've already upgraded to support React 16 there. However, we waited to deploy that support to npm until React 16 got closer to a final release. When a stable version of 16 has been released, we plan to deploy React VR 2.0.0 with full support for React 16. Until then, feel free to build the packages from master by checking out the git repo and running this script: https://github.com/facebook/react-vr/blob/master/scripts/build-packages.js

**Comment by kbrandwijk** [comment]
Thank you very much, that's great news! I'll give that a try, and otherwise I'll be patient...

**Comment by kbrandwijk** [comment]
Building locally, I had a few dev-dependencies missing:
- babel-preset-es2015
- babel-preset-flow
- babel-preset-babili
- rollup-plugin-babel
- rollup-plugin-replace

Not really related to this issue, but just wanted to share it with you.

**Comment by andrewimm** [comment]
Shipped in 2.0.0
