### ISSUE TITLE
[Question] Prevent camera from moving?

### ISSUE THREAD

**Issue by matthamil** [facebook/react-vr#305]
Is there a way to prevent the camera from changing direction when the user clicks and holds and moves the cursor around (or looks around in a headset/rotates a phone)? I don't want to lock the camera indefinitely, but I'm curious if there's a way to toggle the look-around ability on and off.

**Comment by andrewimm** [comment]
Sure, from client.js you should be able to set
`vr.player.controls. nonVRControls.enabled = false`
And setting it to true should re-enable it. You can configure a NativeModule to trigger this from React too, if required.

**Comment by matthamil** [comment]
Awesome! Thanks @andrewimm, and thank you for supporting this library :) I have been really enjoying playing around with WebVR using ReactVR. Keep up the awesome work :tada:
