### ISSUE TITLE
[DOC] Layout and Style [error in tutorial]

### ISSUE THREAD

**Issue by dnalexxio** [facebook/react-vr#308]
in the page
https://facebook.github.io/react-vr/docs/layout-and-style.html

the code doesn't work because it refers to an unknown image, if you use the code from previous examples. 
the line 8 should be
<Pano source={asset('chess-world.jpg')}/>
instead of
<Pano source={{uri: 'office_lobby.jpg'}} />

**Comment by andrewimm** [comment]
Feel free to submit a PR

**Comment by mikearmstrong001** [comment]
fixing in master
