### ISSUE TITLE
there is issue while trying to open the react VR app in  Samsung internet using the gear VR (2016) , I can not see the pano

### ISSUE THREAD

**Issue by marwajawad** [facebook/react-vr#309]
hello All,
I am not able to View/Test the react VR app on  Samsung internet using Gear VR .. I also installed carmel developer view, but I can not see any option to open a browser.. if anyone faced this issue, I will appreciate his/her help

**Comment by andrewimm** [comment]
You should no longer be using the Carmel developer preview. Instead, the new Oculus Browser on Gear supports React VR in full VR mode.

Can you describe your issue in more detail, or provide a screenshot? What exactly doesn't work? Does the same application work as intended on your desktop browser (Chrome/Firefox)?

**Comment by marwajawad** [comment]
the issue that when I add the following code inside init function/ client.js file ,to enable the mic, the App code in the "index.vr.js"  file doesn't load inside the GearVR using "Samsung Internet " or "Oculus" browser:
_vr.render = function() {
     navigator
     .mediaDevices
     .getUserMedia({audio: true})
     .then(stream => {
       // use the MediaStream from the microphone in some way
     })
     .catch(err => {
       // handle error
     });_
   _};_ 
the same code is working perfect in the desktop browser using chrome, the mic function is enabled and  working fine .. I am not able to send screenshot of the issue as it appears inside the gear VR

**Comment by andrewimm** [comment]
You should not be putting that code in your vr.render function. That function runs once per frame (so, 60-90 times every second), and will overload the browser with permissions requests. You should be running it outside of that method.

Unfortunately, none of that code is specific to React VR in any way, so I can't provide any other support. If Samsung browser has issues requesting mic permissions, you should follow up with their support teams, or on stackoverflow.
