### ISSUE TITLE
VideoPano cannot be viewed in headset

### ISSUE THREAD

**Issue by infoxiao** [facebook/react-vr#310]
### Description
I was trying to view a 360 video inside the headset.

#### Expected behavior
I can click on 'View in VR' and put my phone into the Gear VR and device, and the 360 video should play.

#### Actual behavior
The video loads and plays both on desktop, and on mobile (Chrome). But when click on 'View in VR', the screen stays blank white.

Related issue: [#117](https://github.com/facebook/react-vr/issues/117)

### Reproduction

`<VideoPano
          loop={true}
          muted={true}
          autoplay={true}
          source={asset('spain.mp4') } />`

* 'react-vr' package version: 1.4.0
* 'react-vr-web' package version: 1.4.0
* Operating System: MacOS + Android
* Browser: Chrome, and Caramel I think on mobile?
* VR Device: Gear VR

**Comment by infoxiao** [comment]
So digging into different browsers I think this is happening:
1. Once I am on Chrome in mobile (Samsung S7), I think clicking on "View in VR" launches the "Carmel Developer Preview" browser. In this browser, the video doesn't play at all.

2. If I go to the url from the Oculus built-in browser, the video can play. But when I set the video unmute with `this.state.playerState.setMuted(false);`, the video stops playing again

3. If I go to the url from Samsung internet browser launched from Oculus home, the video can play, as well as continues when I set it unmute.

Is there anyway to make sure Oculus built-in browser supports unmuted video?

**Comment by ayalee** [comment]
Facing the same issue here, inserting the phone into Samsung Gear VR, the VideoPano will be rendered as white screen.

Device Information:
Samsung Galaxy S7
Chrome 60.0.3112.107
Android 7.0

**Comment by mikearmstrong001** [comment]
@amberroy do you have any thoughts on this?

**Comment by amberroy** [comment]
Yes we definitely want to support this in the Oculus Browser, last time I tested it was working (although I was on the Galaxy S8).  The URL  you're referring to above is it a public URL that you can share?

**Comment by infoxiao** [comment]
@amberroy the link is not ready to be public but I'm happy to email you.

**Comment by infoxiao** [comment]
It looks like Oculus Internet browser made some updates and now it supports video with sound. Closing this issue now.
