### ISSUE TITLE
Dev Tools Connection Refused

### ISSUE THREAD

**Issue by infoxiao** [facebook/react-vr#311]
### Description

I want to access the Dev Tools described in [https://facebook.github.io/react-vr/docs/dev-tools.html](https://facebook.github.io/react-vr/docs/dev-tools.html)

#### Expected behavior

Should be able to select React Inspector tab

#### Actual behavior

After configuring Nuclide, and started the packager within Nuclide, when navigating to `http://localhost:8081/vr/?devtools`, I got the following error:

`WebSocket connection to 'ws://localhost:8097/devtools' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

### Additional Information

* 'react-vr' package version: 1.4.0
* 'react-vr-web' package version: 1.4.0
* Operating System: MacOS Sierra 10.12.5
* Browser: Chrome Version 60.0.3112.101

**Comment by andrewimm** [comment]
Try using the standalone devtools available by running `npm run devtools` and see if that works
If the websocket in Nuclide isn't open, that may be a devtools / Nuclide issue, and is unfortunately out of our control or scope.

**Comment by infoxiao** [comment]
Turns out it seems only work with the inspector integrated with Nuclide.
So from [command palette](https://atom.io/packages/command-palette), run `Nuclide React Inspector: Toggle`
