### ISSUE TITLE
[Question] Animating Shader Values

### ISSUE THREAD

**Issue by ericseaton-avatar** [facebook/react-vr#312]
I am trying to animate a shader in react VR and can't seem to get the animation going.

`<Box
  dimWidth={1}
  dimHeight={1}
  style={{
    transform: [
      {translate: [-2, 0, -2]},
      {rotateY: '20deg'}
    ],
    color: '#4444ff'
  }}
  lit={true}
  materialParameters={{
    uniforms: {
      'iGlobalTime': { value: seconds, hidden: 1 }
    },
    vertexShader: this.vertexShader,
    fragmentShader: this.fragmentShader,
  }}
/>`

'iGlobalTime' is the value I am attempting to animate above and 'seconds' is coming from state which is set by an interval created on mount. Within render if I log out seconds I can see the value changing but the shader does not animate. Thanks!

**Comment by mikearmstrong001** [comment]
How are you animating this? I probably need some more context

**Comment by ericseaton-avatar** [comment]
I posted up a a gist of my component here: 

https://gist.github.com/cidicles/825471f82a42b205f2c44d8465539b3e

Thanks for checking this out!

**Comment by mikearmstrong001** [comment]
I've found the issue and you see the fix land in master soon. FYI replacing the value of shadermaterial.uniform with the new object meant the internal three.js cache was not pointing at the correct object

**Comment by mikearmstrong001** [comment]
I've fixed this in master
