### ISSUE TITLE
[Questions] Are you able to navigate around in a "room" you created? Or is React VR only a 360degree viewing VR platform?

### ISSUE THREAD

**Issue by 0O7** [facebook/react-vr#323]
### Description
Hi, 

Just putting it out there that I am new to VR and the WebDev world. 

So, I just started looking into React VR and upon some research and having the simple WelcomeToVR set up, I don't a feature to be able to navigate around the virtual room. 

I see in demos of people clicking on hotspots to navigate to a different "room", but I want to be able to use my keyboard keys to navigate around from room to room. Is there a .keypressed method?

Any info will be extremely helpful, thanks!

**Comment by andrewimm** [comment]
Here's a whole thread on moving the camera: https://github.com/facebook/react-vr/issues/15

**Comment by andrewimm** [comment]
Additionally, the easiest way to move the camera around is in the Runtime code, found in client.js. This is just standard JS code, so you have full access to the standard browser event model.

vr.camera() exposes the three.js Camera object.

**Comment by 0O7** [comment]
Thanks for the quick reply! I'll look into it.

**Comment by cherouvim** [comment]
Is this (still) possible in react-360?

Thanks
