### ISSUE TITLE
Doc bug - shadow props link goes to getting started

### ISSUE THREAD

**Issue by jgwinner** [facebook/react-vr#324]
### Description

Documentation bug, missing page https://facebook.github.io/react-vr/docs/shadow-props.html

#### Expected behavior

On the page: https://facebook.github.io/react-vr/docs/vrbutton.html if I click on "Shadow Props" the status bar indicates it links to: https://facebook.github.io/react-vr/docs/shadow-props.html#props

I would expect a page detailing the "Shadow Props"

#### Actual behavior
However, clicking on "Shadow Props" goes to the getting started page with Chrome; (probably the 404 or something), IE gives  a real 404 page. Frankly, this is better, as I thought I clicked on the wrong thing.

"Fries with that?"
"Sure"
"Here's your Birthday cake."
"Huh? Did I order cake?"
"No dear, the server is confused."

### Reproduction

1. Go to https://facebook.github.io/react-vr/docs/vrbutton.html
2. Scroll down the page past the props
style?: style 

Layout Props...
Shadow Props...
Transforms...

3. Click on "Shadow Props..."

### Solution

Find or write the shadow-props.html page. 

### Additional Information

* 'react-vr' package version: Online web page.
* 'react-vr-web' package version: Online web page.
* Operating System: N/A, but Windows, through Chrome, IE, Firefox, and Opera
* Graphics Card: N/A
* Browser: Chrome, IE (all versions, it's a server problem, not a browser problem)
* VR Device: N/A, Documentation issue, not runtime.

**Comment by amberroy** [comment]
thanks for catching this.

**Comment by mikearmstrong001** [comment]
IJust to loop back. Shadow props are not actually supported in react-vr. Were you looking at using them?

**Comment by jgwinner** [comment]
I assume this would map to the LightShadow class in three.js? Not sure how that would map to the VR Button. I was going through the documentation while I'm writing a book on ReactVR for Packt publication. So that's how I stumbled on the broken link.

I'd say remove it. I'll remove it from my draft if you do.

**Comment by mikearmstrong001** [comment]
It isn't the LightShadow, it's actually a style property for views

It has been removed
