### ISSUE TITLE
react-vr Webview inside of React Native app

### ISSUE THREAD

**Issue by kristabell** [facebook/react-vr#325]
I'm not sure if this is already possible, (if so, could someone please provide an example?) but I have the following use case:

I have a react native app and I am using WebView to display a separate React-VR application. In the React-VR application, I would like to be able to click on a (VR)Button, and be redirected to the correct React Native view. WebView allows for onMessage events, but since VRButtons are not DOM elements, I cannot attach a postMessage event to it. I could use Linking in both applications to direct to the correct views, but I don't think that provides a very good user experience as it will display the "Open in..?" prompt while already in the application.

Is there a way to access elements in React VR so that I can attach a postMessage function to an element? If so, could someone please provide an example? Thank you!

**Comment by andrewimm** [comment]
React VR components can communicate with the hosting window in a variety of ways through Native Modules. An example demonstrating this is found here: https://github.com/facebook/react-vr/tree/master/Examples/NativeModules

**Comment by kristabell** [comment]
Thank you for the example! I am trying to get this to work but am now running into the error:

CoreAnimation: [EAGLContext renderbufferStorage:fromDrawable:] was called from a non-main thread in an implicit transaction! Note that this may be unsafe without an explicit CATransaction or a call to [CATransaction flush].

in my React Native project. I also noticed if I try to hit the VR app in a safari browser on an iphone simulator, I get an "A problem repeatedly occurred" error, but it works fine in my local browser.

Has anyone else ran into errors running react-vr in safari in iOS 11?

**Comment by andrewimm** [comment]
Given that iOS 11 is still not stable, I wouldn't be surprised if there's an active issue with Safari right now. React VR has no known issues with iOS 10.

**Comment by davidsalib** [comment]
@kristabell were you able to get this working?
