### ISSUE TITLE
ReactVR loads scenes very slowly. 

### ISSUE THREAD

**Issue by TheMachineHere** [facebook/react-vr#333]
I am using the _"live-tour-lab"_ library. It currently takes about 30 seconds to load a scene.

Is this usually how slow ReactVR is?

FYI my static_assets total up to 38mb, and a scene doesn't require more than 13mb....which isn't a lot.

**Comment by andrewimm** [comment]
In this case, what does "load" mean, and what is a scene? A 360 pano, or a GLTF scene?

React VR is usually instantaneous, you'll see this in the sample apps provided in the repo. The only potential delay is the normal network cost of loading a panorama over the network. I can't comment on live-tour-lab, it's a third-party product that is neither supported nor maintained by Facebook.

**Comment by matthamil** [comment]
@TheMachineHere I have not experienced issues with React VR that were due to React VR itself. Like Andrew mentioned, you're probably loading heavy assets over the wire.

**Comment by TheMachineHere** [comment]
@matthamil have you ever used the live-tour-lab library? Were you able to make fast responsive scenes with it?

**Comment by TheMachineHere** [comment]
Okay, it seems that you are right. Even though my pano and other images aren't too big, they seem to be the factor why its loading so slowly. 

Does react support Caching? 
Can I just make an "asset(uri)" call and then show the image with width and height of 0? 
More Importantly, Is there a method that would tell me when the asset call has finished?

**Comment by andrewimm** [comment]
@TheMachineHere React VR uses the browser's cache, so there should be no need for explicit caching of images / textures.

There is a Prefetch component which you can use to pre-load Panorama assets: https://github.com/facebook/react-vr/blob/master/Libraries/Pano/Prefetch.js
For anything else, just use the standard web technique of instantiating a `new Image()` with the source of the resource you want the browser to load.

Tags like Image and Pano have callbacks that allow you to know when the resource is finished -- look in the docs to find more. Also, to clarify, `asset(uri)` is not a call to load an object, it's just a method that resolves to the proper path of your asset in different environments. It doesn't do any networking itself.

**Comment by andelar** [comment]
@TheMachineHere 

The assets are loaded by the browser, so you can see your file loading progress in Chrome by opening View / Developer / Developer Tools, tab Network. Then you can quite easily spot if it is slow Internet or some other issue. 

Once assets are loaded first time, they will be picked from the browser cache and won't be reloaded, if you have set the Cache control parameters on your web server where you host the files.

On the live-tour-lab repo you can define prefetch on the previous scene, to take advantage of the technique that @andrewimm mentions above. Hence while the the user is in Scene 1, you already load the media for Scene 2. Then when he/she clicks the navigation to Scene 2, the file is already in the browser cache and it will feel like "instant" load even if the file is 10+ MB. See example on the live-tour-lab repo.

I also replied on your question the https://github.com/livetourlab/live-tour-lab 
Happy to help you further if you need.

**Comment by andrewimm** [comment]
Closing since there is no issue with React VR
