### ISSUE TITLE
Catch event rotate real time.

### ISSUE THREAD

**Issue by ngocnguyen09910060** [facebook/react-vr#335]
Hello everybody,
I has an issue. I want to catch event rotate on panorama when user hold and move mouse around panorama. Please help me.
Thanks.

**Comment by amberroy** [comment]
Yes this is possible. You can use `onInput`, which is a property of all views including `<Pano>` to catch the user input.  (If you're looking for button-style, onClick behavior, that is provided by VrButton.)

**Comment by neve71** [comment]
Tell about panorama

**Comment by ngocnguyen09910060** [comment]
Hi amberroy,
I understood `onInput` event. But i only want catch it when user click, hold left mouse and move around. Such as mouseDown, mouseUp,... ?
