### ISSUE TITLE
Ability to request fullscreen on the containing parent rather than glRenderer.domElement

### ISSUE THREAD

**Issue by amitrajput1992** [facebook/react-vr#344]
### Description

Is there a way to request fullscreen from a different element other than the canvas element?
I went through Player.js and OVRui library and couldn't find what I saw looking for. (maybe I missed it!)

Basically, I want to show the overlay HTML elements in fullscreen mode as well, which currently hide as the canvas goes to fullscreen. For ex. the compass element is not visible in fullscreen mode. It makes sense to not show those when getting into VR mode though.

#### Expected behavior
Ability to see HTML overlay in fullscreen mode

#### Actual behavior
HTML overlay is hidden when going into fullscreen mode.

### Solution
Add additional params 'requestFullscreenOnParent' to VRInstance and propagate the same to Player.js to handle fullscreen request.

```
Player.js

attemptEnterFullscreen(fullscreenMethod: string) {
    document.addEventListener(fullscreenEvent, this.handleFullscreenChange);
    const canvas: any = this.requestFullScreenOnParent ? this._el: this.glRenderer.domElement;
    if (typeof canvas[fullscreenMethod] === 'function') {
      canvas[fullscreenMethod]();
    }
  }

```

### Additional Information

* 'react-vr' package version: 1.3.0
* 'react-vr-web' package version: 1.3.0
* Operating System: Linux 
* Graphics Card: Intel HD 6000
* Browser: Chrome 59.0.3071.109, chromium 59.0.3071.109 
* VR Device: None

**Comment by andrewimm** [comment]
We'll consider adding more control over what the fullscreen button does. In the meantime, there is an initialization flag that disables the fullscreen button. You could disable the default one and add your own.

**Comment by amitrajput1992** [comment]
I'll try that out and leave my comments here. Thanks for the input!

**Comment by amitrajput1992** [comment]
@andrewimm closing the issue. I was able to handle fullscreen event using custom handlers. Disabled the default fullscreen button and added my own.

**Comment by Jorybraun** [comment]
@amitrajput1992 how were you able to achieve the full screen?
