### ISSUE TITLE
Add raycasters after init React VR

### ISSUE THREAD

**Issue by ngocnguyen09910060** [facebook/react-vr#346]
Hi everybody,
Because of customer's specify requirement, i must add a raycasters if user want to use it (by click a button), isn't at init time.
This is my code:

function init(bundle, parent, options) {
  const vr = new VRInstance(bundle, 'WelcomeToVR', parent, {
    // Add custom options here
    raycasters: [],
    cursorVisibility: "visible", // Add cursorVisibility
    ...options,
  });
  vr.render = function() {
    // Any custom behavior you want to perform on each frame goes here
  };
  // Begin the animation loop
  vr.start();
  return vr;
}

When user want to use raycasters, i implement:
`vr.guiSys.raycasters = [SimpleRaycaster];`
But it isn't work. Please help me.

**Comment by andrewimm** [comment]
We don't recommend changing the list of raycasters after init time.

Instead, you should take advantage of the fact that raycasters act as a cascade. The code walks through the array until a raycaster returns a non-null value. To control whether a raycaster is "on" or "off," you should have your code determine whether to return `null` or the vector from the origin and orientation methods.
