### ISSUE TITLE
Typo on React VR Overview page

### ISSUE THREAD

**Issue by emshuttles** [facebook/react-vr#348]
Bug: Typo

[React VR Overview page](https://facebook.github.io/react-vr/docs/react-vroverview.html)

In the sentence that reads

> Such events can be handled within the component declaration to properly processes the interaction, for example:

"processes" should be "process"

**Comment by andrewimm** [comment]
React VR is open source. Happy to accept PRs to fix documentation.

**Comment by marcelosuzumura** [comment]
It seems that the original reporter fixed the typo. Please close this issue.

Commit:
`15363f1b (Erik Shuttlesworth    2017-09-21 11:38:36 -0700  66) component declaration to properly process the interaction, for example:`
