### ISSUE TITLE
React-vr licence.

### ISSUE THREAD

**Issue by ksgr** [facebook/react-vr#353]
@andrewimm  Is react vr open source ??

**Comment by andrewimm** [comment]
I just answered this in #352

**Comment by ksgr** [comment]
what is  'Liability' mean to this software..

**Comment by andrewimm** [comment]
Unfortunately, I'm not a lawyer, and am not qualified to provide any legal advice. I recommend that you search elsewhere for plain text explanations of the BSD license.
