### ISSUE TITLE
Image tintColor not working on PNG Image

### ISSUE THREAD

**Issue by lnesi** [facebook/react-vr#355]
### Description
Image tintColor not working on PNG Image

#### Expected behavior
Image with red tint
#### Actual behavior
Image Without Color Change
### Reproduction

  <Image style={{tintColor:'red',width:1, height:1,transform:[{translate:[0,0,-10]}]}}
            source={{uri:'../static_assets/play.png'}}
            inset={[0.2,0.2,0.2,0.2]}
            insetSize={[0.05,0.45,0.55,0.15]} >
          </Image>

An example of your code that reliably reproduces the issue is ideal.

### Solution

the tintColor Style should work as per the documentation.

### Additional Information

* 'react-vr' package version:react-vr@1.4.0
* 'react-vr-web' package version: react-vr-web@1.4.0 
* Operating System: MacOS
* Graphics Card: iMac
* Browser: Chrome
* VR Device: WebVR

**Comment by lnesi** [comment]
My bad This works with White PNG not black PNG

**Comment by jgwinner** [comment]
Sounds like it was a really DARK red. :)
