### ISSUE TITLE
react-vr stopped work in Google Chrome (Android)

### ISSUE THREAD

**Issue by hmontes** [facebook/react-vr#360]
Hi. I have issues with my React-Vr. App. In few hours ago, the react-vr websites don't work good in Android.

I created a new project and the error is the same. But in console i see this.

```
Invalid asm.js: Unexpected token
three.js:19368 THREE.WebGLRenderer 80
```

It's a global problem?

**Comment by andrewimm** [comment]
Is it actually not rendering, or is there just a warning in your console? That warning should be harmless.

**Comment by andrewimm** [comment]
Just did a quick look around, seems like there's a newly-reported bug in Chrome around parsing asm.js generated from Emscripten (this is how we build Yoga from C into JS). If it's a Chrome bug, there isn't much we can do unfortunately.

**Comment by hmontes** [comment]
It's weird. In my windows computer the render works, In my macbook don't.

It's rendering but ... The view start in the bottom, i can't move with the cellphone (only touching the screen) and i can do a flip in the screen (Normally, you can't)

**Comment by andrewimm** [comment]
What version of React VR are you using, and what phone? Can you please provide a screenshot?

**Comment by hmontes** [comment]
Weird. Now works. I don't know where is the problem. 

I'm sorry
