### ISSUE TITLE
[Question] Communication between main thread and Web Worker

### ISSUE THREAD

**Issue by axemclion** [facebook/react-vr#37]
I noticed that you use a web worker to run react reconciliation and react native's batched bridge to communicate between the main and worker thread. 

I also noticed that some of the messages (typically when bootstrapping) passed between UI thread and worker are `JSON.stringified`, while the actual commands related to `exec`, `flush`, and `invoke` (in BRIDGE_CODE in `createRootView.js`) are not `JSON.stringified`. 

I was wondering if you guys have any perf data to indicate that sending plain JavaScript objects for this specific case works better. 

P.S: I was playing with running react on a worker for the DOM, and noticed that JSON.stringify does indeed send messages much faster.

**Comment by andrewimm** [comment]
Hey @axemclion,
You're right that in many cases (excluding Edge and Safari), stringify-then-post is faster than posting a POJO. I've been intending to clean up some of the bridge code to do exactly this, as well as some explicit measurement of time spent across the bridge. Mostly, the code is the way it is right now because some of it is yanked from RN, some of it was written to add some of our needs, and in general we've been pushing for functionality over perf until we reach the full public release. But thanks for bringing this up! I believe stringifying the body will bring some real perf improvements.

**Comment by axemclion** [comment]
Thanks for the response !! I have been playing with [React Web-Worker Performance](http://blog.nparashuram.com/2016/02/using-webworkers-to-make-react-faster.html) for a while and have recently started diving into react-vr, primarily because of the web-worker design. 

Is the perf work you are doing available somewhere to take a look at ? 

I am using the infamous [DBMonster](https://github.com/web-perf/react-vr-dbmonster) as a perf benchmark. Will report back on any findings I have. Some other related questions 

1. Is there a better performance benchmark application that I should instead use ? I am looking to write an automated performance monitor
2. The react-vr-web project is not yet open sourced, and I simply pulled out `node_modules/react-vr-web` and am modifying [that](https://github.com/web-perf/react-vr-dbmonster/tree/master/custom-react-vr). Is that a good starting point ? 
3. I see that the operations currently are added to a queue, and then processed during every requestAnimation frame. Is that set in stone, or would exploring alternatives there make sense ?

**Comment by axemclion** [comment]
Looks like we don't need `JSON.stirngify` hacks anymore - https://bugs.chromium.org/p/chromium/issues/detail?id=148757#c165

**Comment by liorfrenkel** [comment]
Hi @andrewimm ,

I am trying to communicate with the global window from a react-vr app, is there an easy way to do that?
from the app I can only get the `DedicatedWorkerGlobalScope` and there is no access to the main browser's window, and postmessage from the worker does not get to the parent window.

Thanks a lot!
Lior

**Comment by venits** [comment]
If someone is looking for help I have created simple module that makes communication between "Web Worker" and "Main Thread" easy :) 
https://github.com/venits/react-vr-bridge
