### ISSUE TITLE
Live docs page outdated, latest docs in master unpublished

### ISSUE THREAD

**Issue by RadValentin** [facebook/react-vr#382]
### Description

I've noticed that there are quite a bit of changes that have been made to the docs in this repo that aren't present on the main site https://facebook.github.io/react-vr/docs
One example would be that CSSLayout has been renamed to Yoga but [this page](https://facebook.github.io/react-vr/docs/layout-and-style.html) still references the old name despite PR #303 

### Solution

Please publish the latest docs. I'd like to contribute to them but I'm discouraged to so if my changes might not be published.

**Comment by mikearmstrong001** [comment]
thank you, moving discussion over to PR
