### ISSUE TITLE
Oculus browser in Gear VR - History.pushState triggers VR exit

### ISSUE THREAD

**Issue by iox** [facebook/react-vr#388]
### Description

Bug: when using History.pushState (https://facebook.github.io/react-vr/docs/history.html), the Oculus browsers "exits" VR mode, forcing the user to press the back button.

#### Expected behavior

The URL is updated, but the user can stays in VR mode. This works fine in other browsers, like in "Samsung Internet".

#### Actual behavior
The VR mode is "stopped".

### Reproduction
Example code:
```
nextPage = function(){
    var url = this.state.data.navigation.pagination_link+this.state.data.navigation.next_page
    if(!BrowserInfo.userAgent.includes('OculusBrowser')){
      this.props.History.pushState("", "gallery", this.props.baseURL+"?handle="+this.props.handle+"&url="+encodeURIComponent(url)+"&component=gallery")
    }
    this.loadData(url)
  }
```

### Solution
We are using a workaround by disabling pushState with Oculus browser (see example code).

### Additional Information

* 'react-vr' package version: 1.4.0
* 'react-vr-web' package version: 1.4.0
* Operating System: Android - Samsung Galaxy S8
* Graphics Card: --
* Browser: Oculus Browser
* VR Device: Samsung Gear VR

**Comment by andrewimm** [comment]
Sorry, Issues on this repository are for React VR only, and have nothing to do with Oculus Browser. If it works fine on other browsers, that does not sound like a library bug.

**Comment by andrewimm** [comment]
Followed up with the Oculus Browser team, they have found the cause and a fix will be released in an upcoming version.

**Comment by iox** [comment]
Wow, that's fantastic @andrewimm , thanks a lot for contacting the Oculus Browser team!

**Comment by zzz6519003** [comment]
@andrewimm can i help to do some translation in Chinese? there're vast talented coder here XD

**Comment by natesena** [comment]
@andrewimm I am unable to get the History API to be recognized in any way. I've imported {HIstory} from 'react-vr' and even followed this implementation: https://developer.oculus.com/documentation/vrweb/latest/concepts/carmel-navigation/
but history is not part of the window object, and does not seem to be its own component. Can an example be written on the docs?
