### ISSUE TITLE
A large amount a OBJ cannot be loaded as a Model

### ISSUE THREAD

**Issue by JohnCoding94** [facebook/react-vr#390]
### Description

I tried to display some objects from the poly google lib i just discovered, and a lot of them make react-vr displaying an error when trying to load them.

#### Expected behavior

Be able to load any model from [the Poly Google library](https://poly.google.com).

#### Actual behavior

An error occurs so the model is not displayed (with 4/5 models i tried from the library), here is the error:

Failed to fetch resource: "../static_assets/models/<MY_MODEL>/model.obj".

The first line of the stack trace is: (anonymous) | @ | ObjModelLoader.js:115

### Reproduction

Just try to display this model for example: https://poly.google.com/view/aSeRYpWIbqV

Here is the render:

``` js
<View>
  <Model
     style={{
       transform: [
         { translate: [-25, 0, 0] },
         { scale: 100 },
         { rotateY: 0 },
         { rotateX: 20 },
         { rotateZ: -10 }
       ]
     }}
     source={{
       obj: asset('models/chip/model.obj'),
       mtl: asset('models/chip/materials.mtl')
     }}
   />
</View>
```

### Solution

I really don't know, i am just discovering the framework...

### Additional Information

* 'react-vr' package version: 2.0.0
* 'react-vr-web' package version: 2.0.0
* Operating System: MacOS
* Graphics Card: AMD Radeon
* Browser: Chrome 62.0.3202.75 
* VR Device: Out of VR

**Comment by mikearmstrong001** [comment]
where is the model located, in the static_assets folder oh did you place elsewhere
it looks like it is failing to fetch the resource rather than got into parsing

(although I'm just checking that out)

**Comment by JohnCoding94** [comment]
@mikearmstrong001 

Yes i put this "models" folder into my "static_assets" folder.

Once again i am able to load some models, with the exact same path structure: "static_assets/models/<DYNAMIC_NAME>/model.obj" and "static_assets/models/<DYNAMIC_NAME>/materials.mtl".

It looks like the "ObjModelLoader" service is not able to load any kind of ".obj" models when Google is able to display it on their library's website (so the model looks to not be corrupted itself), but i have no idea how this part works yet.

Are you able to display [this model](https://poly.google.com/view/aSeRYpWIbqV) on your side ?

Thanks for your help !

**Comment by mikearmstrong001** [comment]
The error was that the negative indexes in the obj file were incorrectly handled. I've submitted a fix.
sorry for the delay.

**Comment by JohnCoding94** [comment]
Great thanks ! Could you please link the PR ? I am curious to see the patch :)

**Comment by mikearmstrong001** [comment]
No PR as it landed in a regular commit :)

**Comment by JohnCoding94** [comment]
Ok i have found the commit yesterday, thanks !

**Comment by Alwox** [comment]
I have the same problem with my model from Google Blocks app. I edited those 2 lines from your commit in my `node_modules` in `react-vr-web` folder but nothing changed. I'm doing something wrong or this could be a different problem?

**Comment by jgwinner** [comment]
Do you have negative indexes in the .OBJ file?  (It's text, you can scan it). 

Do you get the same error?

Can you post the model?

**Comment by Alwox** [comment]
Yes, I have negative indexes. Sure, here you have both (because in a folder after saving the project I have two .obj files) 
[react_logo.zip](https://github.com/facebook/react-vr/files/1609129/react_logo.zip) (i was trying to made react logo for test - it's my first 3D model so.. 😄 )

**Comment by jgwinner** [comment]
Again, what error messages are you getting?

I don't think you have negative indexes; that means a face statement like
f 1/2/-3

Taking a quick look, your .obj file says:
`mtllib materials.mtl`
so if you don't have that file, it won't load.

Also, it looks like you have groups in there. It imported into Blender OK, but Blender is going to be a little more forgiving for bad files or missing materials. You might want to group all 3 objects into one top level object, unless you wanted to animate them separately. I haven't tried importing animations, I prefer to use gltf for that.

**Comment by Alwox** [comment]
`ObjModelLoader.js:115 Failed to fetch resource: "../static_assets/models/react/model.obj"`
🤔 actually in Blocks folder for this model I have more files, those two `.obj`, `.mtl` (i'm also importing it), there is also `.gltf` and few more so.. what should I import in this case?

**Comment by jgwinner** [comment]
Can we see the code? This is why there is a template for bug reports.

I like .gltf, as you have more material options, but I can't tell you what you 'should' import. As near as I can tell either .obj or gltf should work OK. What is your modeler?

**Comment by Alwox** [comment]
`
<Model
  source={{
    obj: asset('models/react/model.obj'),
    mtl: asset('models/react/materials.mtl'),
  }}
/>` im not sure if rest of code make difference because with different .obj file it works, i have only problem with those from Google Blocks. What do you mean by `modeler`?

**Comment by NhanBlack** [comment]
this obj no color in react vr

**Comment by rafalfaro-hangar** [comment]
The mtl files are the problem. Not all of them are supported, in that case it will render the object black and not responsive to ambient light. Try first loading objects without material and coloring with style. The try textures as a last step when you're already sure everything else is working.
