### ISSUE TITLE
VrButton does not display on any browser

### ISSUE THREAD

**Issue by Samartan** [facebook/react-vr#403]
### Description
I am new to react-vr and I am trying it out. So, after I successfully ran the WelcomeToVr on my chrome, I thought of adding a button to it and experimenting a bit. But then when I use the vrButton in my code. It never appears on the screen. No errors are thrown anywhere expect a warning that says "Invalid asm.js: Unexpected token". I do not know where to start looking as there are no errors related to it that pops up. 
I can provide you with any other details required. Thank you.

#### Expected behavior
A VrButton must be displayed.
#### Actual behavior
No VrButton is displayed
### Reproduction

Follow all the steps in the standard WelcomToVR tutorial with a Vrbutton used in the code.

### Solution

What needs to be done to address this issue? Ideally, provide a pull request with a fix.

### Additional Information

* 'react-vr' package version: 2.0.0
* 'react-vr-web' package version: 2.0.0
* Operating System: MacOS
* Graphics Card: Intel HD Graphics 6000
* Browser: Chrome
* VR Device: Browser

**Comment by jgwinner** [comment]
You normally 'wrap' the VrButton around visible geometry; this lets you make anything interactive.

So if you want a box, for example, to represent a button, you make a `<Box> `be a child object of the `<VrButton>`

Does that make sense?

The docs sort of imply that, although maybe it could be more obvious.

>  By default, a VrButton has no appearance and will only act as a wrapper to capture events, but it can be styled in the same ways as a View.

2D GUI's do not work well in VR; they can fatigue you, and bring up many issues in a true 3D world. VrButton allows you to make actual objects interactive.
