### ISSUE TITLE
Question: Facebook Integration example

### ISSUE THREAD

**Issue by jgwinner** [facebook/react-vr#413]
### Description

Feature Request

### Documentation 

Is there a way to embed React VR apps inside a FaceBook page? If so, a general link in the documentation would be great or a sample.

I've seen Sony, for example, doing it on FaceBook. Is it possible with Developer pages?

**Comment by andrewimm** [comment]
The work we did with Sony was limited to a few launch partners, sorry. As of right now, there's no way for a developer to embed their own application directly into Facebook, since that could pose a variety of security or performance issues.

**Comment by jgwinner** [comment]
Understood, that's what I was afraid of.

Is there any way that the FaceBook developer community could maybe have a vetted process of including React VR somewhere? Maybe after a performance / compliance review?

I realize this is above this group's charter, more than likely. Where could I/we put in this request?

**Comment by andrewimm** [comment]
Rest assured, your request is heard and I'll pass it along.
I can tell you that our work so far with those initial developers is part of a broader effort to understand the types of experiences that developers and content producers would like to see in newsfeed. Once we have a better grasp of the types of content that are optimal for this embed experience, we plan to design a system around those common applications and explore ways to open this up to content creators. Obviously I can't commit to delivering anything, or even what such a product would look like in the end, but it is something we are actively working on.

One option you do have today involves Facebook hosted games (https://developers.facebook.com/docs/games/gamesonfacebook/hosting). These allows you to distribute HTML5 content as part of Facebook's app center. This is oriented around games and social applications, but there is no reason that you could not build these things with React VR.

**Comment by jgwinner** [comment]
Thanks Andrew! I'll check it out.

Knowing the best way to go, with the wealth of FaceBook opportunities, helps a lot.
