### ISSUE TITLE
Problem with implementation of draggable views.

### ISSUE THREAD

**Issue by venits** [facebook/react-vr#415]
### Feature Request

Hi,
I am trying to create draggable view. I found at the bottom of this page: [Animated](https://facebook.github.io/react-vr/docs/animated.html), class called **DraggableView**. I implemented it like this:
```javascript
import React, { Component } from 'react';
import { Animated } from 'react-vr'
import { PanResponder } from 'react-native';

export default class DraggableView extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      pan: new Animated.ValueXY(), // inits to zero
    };
    this.state.panResponder = PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onPanResponderMove: Animated.event([null, {
        dx: this.state.pan.x, // x,y are Animated.Value
        dy: this.state.pan.y,
      }]),
      onPanResponderRelease: () => {
        Animated.spring(
          this.state.pan,         // Auto-multiplexed
          {toValue: {x: 0, y: 0}} // Back to zero
        ).start();
      },
    });
  }
  render() {
    return (
      <Animated.View
        {...this.state.panResponder.panHandlers}
        style={this.state.pan.getLayout()}>
        {this.props.children}
      </Animated.View>
    );
  }
}
```

Sadly I can't get draggable view. 
I think I am missing something because it works in React Native.

**In Vr panResponder functions are not called**. I was thinking that id my be due to mouse-drag camera rotation, so I disabled it like this:
```javascript
  vr.player.controls.nonVRControls.disconnect();
```
but still it's not working.

Also I am wondering is it possible to create draggable view with panResponders or I should do it in more brutal way using **onMove** function and then use **transform:[]** in style of component?

*Any tips are highly appreciated ;)*

**Comment by andrewimm** [comment]
I do not believe that panResponders are implemented at this time. They're actually designed for 2d touch screens, and don't necessarily translate well to VR space. We're currently rethinking some of the way we implement panels in React VR, and it may be possible to do this in the future, but at this time your best bet is to use `onMove` as you mention.

One option to also consider is something I've done with 6dof Oculus Touch controllers, which may be much more performance-friendly depending on your situation. When I fired the "grab" event, I removed the element from the scene, mounted it at a different React Root attached directly to my 3d Hand object (which I updated each frame directly in the runtime, so no need to run per-frame React updates), and when I "released" the object I reattached it to the original scene at the new coordinates. You can view an example of multiple react roots here: https://github.com/facebook/react-vr/tree/master/Examples/MultiRoot

**Comment by venits** [comment]
Thanks for quick response. I should be able to solve my problem right now :)

**Comment by venits** [comment]
I have one problem when I want to "release" object back to original scene with new coordinates.

I know how to get camera rotation at the moment of releasing grab and them I am trying to calculate new x, y, z coordinates based on those rotations. 

Calculations are quite complex and I am not getting perfect result :( There is always some shift and bad rotation at the end.

I am wondering if there is easier way to put view back or I should improve my math skills first and then try to calculate it correctly?

**Comment by venits** [comment]
I found something interesting that may solve my problem for now:

There is prop we can send with View:
```javascript
billboarding="on"
```  

Looks promising. I will play with it a little and hope to get good results :)

**Comment by jgwinner** [comment]
Hey, it would be great to see the solution :) 

== John ==

**Comment by venits** [comment]
Hi @jgwinner
Like Andrew mentioned you need to mount additional component (You can call it hand).
More info here: https://github.com/facebook/react-vr/tree/master/Examples/MultiRoot

Then simply on grab you unmount your view from main component and mount it in hand component.
When user click on view again you unmount view from hand and mount it to your original view.

The most tricky part is to calculate new coordinates.
You can use:
```javascript
VrHeadModel.rotation()
```
to get rotations on grab release.

Based on that you can calculate new x, y and z coordinates.

Sadly is not working perfectly because I think I am not doing math correctly.
I am still improving it but I think by the end of this week I will create GitHub repo with solution :)

**Comment by kwegorek** [comment]
@venits do you have a code example showing how to drag and drop Entity/View/VrButton in react360?

You mention `onMove`? It doesn't seem like it's a property of aforementioned.
