### ISSUE TITLE
Mobile Safari and Mobile Chrome on iOS can't handle Mesh

### ISSUE THREAD

**Issue by LennonR** [facebook/react-vr#42]
### Description

I'm developing off the basic WelcomeToVR project and I've added some mesh objects around my simple scene.  Everything looks great on desktop but when I try to view in mobile iOS safari or mobile iOS chrome, I get a black screen with the little radar on the right.  If I remove the Mesh objects, the scene renders just fine on mobile.  

#### Expected behavior

The scene would render on mobile exactly as on desktop.

#### Actual behavior

Black screen.

#### Logs

Not sure how to get mobile logs.

### Reproduction

Add a Mesh to the WelcomeToVR project and try to view on mobile iOS Safari or Chrome.
### Additional Information

* react-vr package version: ~0.1.0
* react-vr-web package version: ~0.1.0
* Operating System: iOS 10.2
* Graphics Card: whatever comes standard with iPhone 6S
* Browser: Mobile Safari 10.0 and Chrome Mobile iOS 49.0.2623
* VR Device: N/A

**Comment by LennonR** [comment]
Just tested this with an Android Samsung Galaxy 5 and Chrome and it worked fine.

**Comment by mikearmstrong001** [comment]
Thanks, will check this. FYI to track these problems I usually use Safari's web inspector which allows you to debug a usb connected iOS device.

Was this on all meshes including the MeshSample that we provided?

**Comment by LennonR** [comment]
@mikearmstrong001 I just tried with the regular Mesh Sample from the preview folder and same issue. Works fine with my android test device and on desktop.  Also, attached is a screenshot of the debugging console.  There is an error.

![mobilesafarimeshbug](https://cloud.githubusercontent.com/assets/916139/22295192/0b9bfa5e-e2e4-11e6-95d8-ebc998b0fb2a.png)

In case it matters, I'm using ngrok to do the localhost tunneling.

**Comment by amberroy** [comment]
Thanks I'm able to repro this as well, will investigate.

**Comment by gaelduplessix** [comment]
Turns out it's just Safari missing `fetch` support. I tried adding a [polyfill](https://github.com/github/fetch) and it works nice :)

All you have to do is include [this file](https://github.com/github/fetch/blob/master/fetch.js) in `MeshSample/vr/index.html`. You can do this by copying it next to `index.html` and adding this script tag before any other scripts:
```html
<script src="./fetch.bundle?platform=vr"></script>
```

**Comment by johnnyshankman** [comment]
I can attest to @gaelduplessix, it's Mobile Safari's lack of `fetch` support.

Polyfill will work, but I suggest doing `npm install whatwg-fetch --save-dev` and then adding `import 'whatwg-fetch'` to `client.js` so that the Mobile Safari client side has a polyfill for fetch.

**Comment by andrewimm** [comment]
RN Packager should have been polyfiling the fetch API where necessary when it does all the other ES6 polyfilling. I'll check the packager pipeline.

**Comment by andrewimm** [comment]
Fixed in a previous release.
