### ISSUE TITLE
HTML5 Form Elements

### ISSUE THREAD

**Issue by rmendelovits** [facebook/react-vr#421]
### Description

Feature Request

### Solution

Create all the form elements in HTML5 for VR. textarea, checkboxes, radio butttons, and more.

**Comment by andrewimm** [comment]
My belief is that these types of components should be provided as add-ons to React VR, and are not part of the core framework.
Down the road, the React VR team may explore providing a separate package that supplies these, but at the moment it's not on our current list of priorities. In the meantime, we encourage the community to develop these sorts of things on top of React VR. There are already great examples of some of these (like text input complete with virtual keyboards).
