### ISSUE TITLE
Models in React-Vr can't appear Color

### ISSUE THREAD

**Issue by NhanBlack** [facebook/react-vr#423]
i using file obj at link https://free3d.com/3d-model/csgo-m4a4--91075.html with code 
   <AmbientLight intensity={ 2.6 }  />
                <Model
                	  style={{
                      transform: [
                        {translate: [-25, 0, 5]},
                        {scale: 0.5 },
                       
                        {rotateX: 20},
                        {rotateZ: -10}
                      ],
                    }}
                source={{
                  obj: asset('m4a1.obj'),
                }}
                lit={true}
              />
but i don't see  color. please help

**Comment by NhanBlack** [comment]
i try with other obj and mtl file https://poly.google.com/view/5teci4b6krG
but in react-vr i see all black color

**Comment by Nimmimarco** [comment]
add some light, for example PointLight, or disable lit

**Comment by NhanBlack** [comment]
yes i have <PointLight>

**Comment by jgwinner** [comment]
They work fine for me, you have to make sure the objects have the right materials and you've got lights that shine on the objects. Use a directional light - spotlights might still be bugged (they always point 'at' 0,0,0). Not sure on that.

Check your .mtl materials - you might need to examine them in the .mtl file itself; not all exporters create correct materials.

**Comment by rafalfaro-hangar** [comment]
The mtl files should have Kd values. Otherwise it will render a black object. This happened to me exporting with Maya 3D, I just added 0.50 manually (Maya will write 0.00).
```
newmtl blinn1SG
illum 4
Kd 0.50 0.50 0.50
Ka 0.00 0.00 0.00
Tf 1.00 1.00 1.00
map_Kd abstract-art-background-207300.jpg
Ni 1.86
Ks 0.50 0.50 0.50
```
