### ISSUE TITLE
`npm starts` after opening url http://localhost:8081/vr/index.html give 403 Forbidden

### ISSUE THREAD

**Issue by csbug** [facebook/react-vr#425]
### Description

i have tried to run example react-vr app
i have followed all the steps in getting started guide

[getting started](https://facebook.github.io/react-vr/docs/getting-started.html)

npm install -g react-vr-cli
 react-vr init WelcomeToVR
 cd WelcomeToVR
npm start

Open your browser to http://localhost:8081/vr/index.html.

but it gives me **403 Forbidden**

in terminal it shows 

`$ npm start

> vrApp@0.0.1 start D:\hgs-project\JAN2018\reactVR\vrApp
> node -e "console.log('open browser at http://localhost:8081/vr/\n\n');" && nod                                                                                                    e node_modules/react-native/local-cli/cli.js start

open browser at http://localhost:8081/vr/

 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   D:\hgs-project\JAN2018\reactVR\vrApp

React packager ready.

Loading dependency graph, done.
`

**Comment by mikearmstrong001** [comment]
I've been unable to repro your problem, my test machine was on a mac.

Can you provide more details, version of npm, yarn, dev machine, etc as without this information we will be guessing.

**Comment by csbug** [comment]
Hi Mike,

Thanks for reply.
i am trying to run react-vr app on 64 bit Windows 8.1 machine.
node version : 8.9.4
npm : 5.6.0
yarn : v0.27.5
![version](https://user-images.githubusercontent.com/2268997/34705866-6ae9de7a-f4fb-11e7-9945-b88bbe78d7f8.png)

![react-vr](https://user-images.githubusercontent.com/2268997/34705865-6adef898-f4fb-11e7-9c33-5660edea1706.png)

![browser-react](https://user-images.githubusercontent.com/2268997/34705872-78adacc6-f4fb-11e7-91e2-4edf9bbf411b.png)

**Comment by csbug** [comment]
Hi Mike,

I found problem, the port number 8081 is being used by  mcAfee Antivirus.
i have made changes in **node node_modules/react-native/local-cli/cli.js**  _default_ port no to _8087_ 

now its working.

Thanks

**Comment by list1223** [comment]
good resolve

**Comment by csbug** [comment]
another solution i found: 
insted of npm start we can run command

**npm start --port 8087**

(in this case no need to change any module files.)
