### ISSUE TITLE
Animation just call 1 time. how to call more times in slideshow

### ISSUE THREAD

**Issue by NhanBlack** [facebook/react-vr#427]
<Animated.Image style={{ borderRadius: 0.2, width: '100%', height: '100%', opacity: this.state.fadeIn, transform: [{ translateX: this.state.slideLeft }] }}
source={{ uri: slide[0] }} />

=> animation just call 1 time. how to call more times if click button next and change source={{ uri: slide[1.2.3.4.5....] }} />

**Comment by larrylin28** [comment]
You can just use JS logic to control the animation to play more times.
For more details on controlling animation, check the animation docs of React Native:
https://facebook.github.io/react-native/docs/0.48/animations.html#docsNav
