### ISSUE TITLE
Question: React VR slide decks??

### ISSUE THREAD

**Issue by jgwinner** [facebook/react-vr#430]
Hi

I am giving a 15 minute presentation on React VR to an industry group.

Does anyone have a 'slide deck' or product collateral that I could use for this presentation?

I don't have an issue coming up with my own (partly based on my book), but would be nice if we presented a consistent approach.

Thanks,

== John ==

**Comment by mpochiro** [comment]
I just did a presentation on react vr and react ar, in my slides I went over the basics of react vr and some dependencies that are present with the ‘hello world’ project that’s available on the react vr github, if you’d like I can send you my PowerPoint

**Comment by jgwinner** [comment]
Oh thank you, that would be fantastic.

I have 15 minutes. I'm giving a web presentation for the VR/AR Association. 

I think you can email me here, I"ll shoot you my real email.

== John ==

**Comment by jgwinner** [comment]
My email is John@gwinner.org

I'll delete this note in a few days so I don't get spammed

**Comment by mpochiro** [comment]
Yessir that should work, do you have any experience in making a React app
and stuff like that? It’s literally a few lines of cli in your terminal and
then bam you created a vr site

**Comment by mpochiro** [comment]
Here are my slides, I’m also looking for a job in AZ so if there’s any
people out there let them know!!

**Comment by jgwinner** [comment]
Yep, I'm creating a VR site, and will put the demos from my book up on it too (with some advanced functionality I didn't have room for in the book).

== John ==
