### ISSUE TITLE
http.... has been blocked by CORS policy: No 'Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by NhanBlack** [facebook/react-vr#432]
I get issue when deloy to hosting:
Access to Image at http.... from origin 'http....' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http:....' is therefore not allowed access.

**Comment by bodo22** [comment]
I suggest you read about what CORS is [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) and then implement headers on the appropriate image requests. Your error has nothing to do with react-vr.
Alternatively, you can host the image on the same server the react-vr app is being served from.

**Comment by HuiguangChu** [comment]
two simple ways to fix: 
a. find a jsonp lib
b. enable CORS on your server side configuration

**Comment by ricardomcardoso** [comment]
Any Example?
All documentation about react ajax calls ignore cors problem.

**Comment by algion** [comment]
https://stackoverflow.com/questions/43871637/no-access-control-allow-origin-header-is-present-on-the-requested-resource-whe/43881141#43881141
