### ISSUE TITLE
ObjParser.js readPoints function fails on valid exponential notation.

### ISSUE THREAD

**Issue by ghost** [facebook/react-vr#435]
### Description

Is this a Bug or a Feature Request?

Bug, attempt to load a model from an OBJ file containing exponential notation in which the exponent is prefixed by a capital `E` instead of lower case `e`.

#### Expected behavior

Should successfully parse.

#### Actual behavior

Fails causing the calling promise to fail with an ambiguous error `Failed to fetch resource:`

### Reproduction

1. Take a valid object file change a vertex in the file to exponential notation using `E`.
2. Attempt to load the file.

### Solution

Alter the regular expressions `POINTS_TEST` and `TEXTURE_POINTS_TEST` to accept capital letters.

### Additional Information

* 'react-vr' package version: 2.0.0
* 'react-vr-web' package version: 2.0.0
* Operating System: Mac
* Graphics Card: Intel Iris Graphics 6100 1536 MB
* Browser: Chrome
* VR Device: N/A (HTC Vive, but connected to another machine)

**Comment by larrylin28** [comment]
I wonder why your .obj file has capital E for exponential notation. Where is the .obj file generated from?
Just want to make sure it's a fair case we'd like to support.
If you like to submit a pull request, we are happy to accept if it makes sense.

**Comment by hansoksendahl** [comment]
It came from the Google Poly.  I believe that Google Blocks may be exporting files in this format as 8 of 8 responses in my call to Google Poly's list endpoint had capital `E` in the vertices data.

**Comment by hansoksendahl** [comment]
**NOTE** since I am working on an app which leverages Google Poly assets this is a blocking bug for me.

**Comment by larrylin28** [comment]
@hansoksendahl that make sense, we are not able import pull request right now, will do as soon as we are able to.
