### ISSUE TITLE
VideoPano issue with large files

### ISSUE THREAD

**Issue by aziliak** [facebook/react-vr#437]
I am trying to play a large 360 vr video file using the VideoPano option. The file size is about 600MB and I am getting some sort of timeout error when executing 'npm start'.  I don't have any issues playing a 15MB video file.

"Loading dependency graph...(node:15008) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): #<Object> (node:15008) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."

Not sure how to properly handle this error (I am a beginner at programming). Anyone else come across this or know how to handle it?  Being able to use large mp4 files is a make or break for me using ReactVR.

(Windows)

**Comment by larrylin28** [comment]
This looks like a issue of React Native Metro Bundler. The log you attached doesn't offer the correct information, it's only about an error is thrown in a Promise. Can you attach more details of logs above or below those lines?
And to unblock you, have you try using mpeg-dash instead of one single .mp4 file?(That will also improve the streaming broad-width.) See the (dash example)[https://facebook.github.io/react-vr/docs/video-player.html#dash-example]

**Comment by aziliak** [comment]
Thank you for the quick response.

I am not seeing any more details regarding the issue that is occurring.  Not sure how to did deeper into the error that is being generated.  There is nothing above / below in command prompt.

![image](https://user-images.githubusercontent.com/12801295/35526938-1f95b7bc-04f7-11e8-9935-a133443b5bd8.png)


With regards to the mpeg-dash, how is this file created?  And does the dash example work for the PanoVideo?  Can this be created using Adobe Premiere?

**Comment by larrylin28** [comment]
Are you referencing the .mp4 file(using `import` or `require`) in any of your js code? I wonder why having a big mp4 file will cause issue in packager.

And for Mpeg-Dash, I think you can try using ffmpeg to encode the video you generated from Premiere. https://blog.streamroot.io/encode-multi-bitrate-videos-mpeg-dash-mse-based-media-players/

**Comment by aziliak** [comment]
I started a brand new project and the following is all of my code.  I only took out the Pano image and added PanoVideo (video is approximately 600MB).  What is weird is that after I try running the command npm start and receive the error, I can change the video source to something and and the error won't go away until I remove the large video file from the static_assets folder :

import React from 'react';
import {
  AppRegistry,
  asset,
  Pano,
  Text,
  VideoPano,
  View,
} from 'react-vr';

export default class testing extends React.Component {
  render() {
    return (
      <View>
        <VideoPano source={{uri: '/static_assets/vrvid2.mp4'}} />
        <Text
          style={{
            backgroundColor: '#777879',
            fontSize: 0.8,
            fontWeight: '400',
            layoutOrigin: [0.5, 0.5],
            paddingLeft: 0.2,
            paddingRight: 0.2,
            textAlign: 'center',
            textAlignVertical: 'center',
            transform: [{translate: [0, 0, -3]}],
          }}>
          hello
        </Text>
      </View>
    );
  }
};

AppRegistry.registerComponent('testing', () => testing);

**Comment by aziliak** [comment]
I did encounter the following error when trying to place a large file in the static_asset folder while viewing the webpage on local host.

jest-haste-map: watch error:
  RangeError: "size" argument must not be larger than 2147483647
    at Function.Buffer.allocUnsafe (buffer.js:253:3)
    at tryCreateBuffer (fs.js:528:21)
    at Object.fs.readFileSync (fs.js:568:14)
    at module.exports (C:\Users\alexz\Desktop\videoplayer\testing\node_modules\metro-bundler\node_modules\jest-haste-map\build\worker.js:59:42)
    at Promise (C:\Users\alexz\Desktop\videoplayer\testing\node_modules\metro-bundler\node_modules\jest-haste-map\build\index.js:492:7)
    at new Promise (<anonymous>)
    at _workerPromise.message (C:\Users\alexz\Desktop\videoplayer\testing\node_modules\metro-bundler\node_modules\jest-haste-map\build\index.js:491:7)
    at HasteMap._processFile (C:\Users\alexz\Desktop\videoplayer\testing\node_modules\metro-bundler\node_modules\jest-haste-map\build\index.js:404:42)
    at changeQueue.then (C:\Users\alexz\Desktop\videoplayer\testing\node_modules\metro-bundler\node_modules\jest-haste-map\build\index.js:705:32)
    at <anonymous>



Should I be putting my src files somewhere else and loading them differently?

**Comment by mpochiro** [comment]
Do you actually have a snippet of your index.vr.js file?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aziliak** [comment]
My post above includes the entire index.vr.js file.

**Comment by mpochiro** [comment]
Sorry I’m completely blind or dumb apparently, you’re importing the video through static asset, do you know if you break that out into a component and then set it up as an asset it’s pulling from a component works?

**Comment by aziliak** [comment]
I'll learn how to do that I guess.  Very new at this.  I'll try to complete what you asked me to do and see what happens.  May be a while before I get back to you.  Thanks for the tip.  I have to figure this out for a presentation and any help is welcome.

**Comment by larrylin28** [comment]
@aziliak This is possibly like an issue with the metro bundler of  React Native. I've reached out to them to get a better idea. I think the basic issue is actually the bundler tried to read the video file which it shouldn't. 
For a work around for you presentation, I'd recommend to put your video not in the project. 
E.g, if you are running this locally on your machine, try host it somewhere else with a http server(like [this](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb?hl=en)), and change the uri from `/static_assets/vrvid2.mp4` to the http address of the video file.

**Comment by aziliak** [comment]
Ok.  I am going to keep trying to work on this issue.  The video doesn't seem to be loading when I have it outside of the static_assets folder.  Below is the code I use to try to load the video as the Pano.  I am able to go to the 127.0.0.1:8887 link and have the video play, but it doesn't seem to load in ReactVR.

<VideoPano source={{uri: 'http://127.0.0.1:8887/vrvid.mp4'}} />

**Comment by mpochiro** [comment]
I was thinking about this video, is it a true pano? Like true 360 video?

**Comment by aziliak** [comment]
Yes.  I have tried with both a side-side pano and a top-bottom pano.

I was able to get a video to play within the asset folder but now I am having troubles playing the video from a different source location (one that a created using larrylin28's comment regarding the http server).

Below is the code that I am trying to use to load the video file.  The same video will play correctly when within the assets folder (but this video is only 1MB).

<VideoPano source={{uri: 'http://127.0.0.1:8887/vrvid.mp4'}} />

**Comment by larrylin28** [comment]
@aziliak I guess you didn't get cross origin access. Checking the browser console, did you get error message about CORS? If you are using the server I recommended, try "Show Advanced Settings" -> "Set CORS headers" and then restart the server.

**Comment by aziliak** [comment]
@larrylin28 That seemed to do the trick!!! :)  Going to have to play around with figuring out the media controls for this... but the video plays and I'm pretty happy to get out of the rut I was in.

Thank you very much for all of the help you have given to me.  I'm sure I will have more questions in the future, but this gives me hope that ReactVR will work for what I am needing.
