### ISSUE TITLE
This <head> element should be </head>

### ISSUE THREAD

**Issue by SeanBannister** [facebook/react-vr#447]
This `<head>` element should be `</head>`:

https://github.com/facebook/react-vr/blob/1afbcf5404b316c11c5d79f81e333430988eb0b1/Examples/VideoSample360/vr/index.html#L6

**Comment by andrewimm** [comment]
Please feel free to submit a PR to fix it. Since this is just an example and isn't broken, I will close out this issue in the meantime.
