### ISSUE TITLE
Change a sentence within the layout and style docs

### ISSUE THREAD

**Issue by sean-ww** [facebook/react-vr#450]
### Description

Bug
https://facebook.github.io/react-vr/docs/layout-and-style.html#layout-and-style

The sentence needs changing
'The library we use, CSSLayout, **tries to follows** the web implementation of flexbox as much as possible.'

Either: 
'The library we use, CSSLayout, **follows** the web implementation of flexbox as much as possible.'
or
'The library we use, CSSLayout, **tries to follow** the web implementation of flexbox as much as possible.'

**Comment by andrewimm** [comment]
This kind of documentation fix is better addressed by sending a quick PR. Please feel free to do so.
