### ISSUE TITLE
[Question] How to rotate a Mesh with respect to its center?

### ISSUE THREAD

**Issue by louisgv** [facebook/react-vr#63]
### Description

I was trying to make a cube rotate with respect to its center. I followed the MeshSample project. I tried changing all the available documented props as well as this:
```
layoutOrigin: [0.5,0.5,0.5],
```   

But nothing changed. 

#### Expected behavior

The mesh should  rotate around its center..

#### Actual behavior

The mesh still rotates around its left anchor.

### Additional Information

* react-vr package version: ~0.1.0
* react-vr-web package version: ~0.1.0
* Operating System: Linux, Ubuntu
* Graphics Card: NVIDIA,
* Browser: Chromium Version 56.0.2924.76 Built on Ubuntu , running on Ubuntu 16.04 (64-bit),
* VR Device: N/A

**Comment by andrewimm** [comment]
Apologies for the confusion, but layoutOrigin is for performing 2d layout and does not use a third dimension. I'll attempt to trigger something in the code

Transforms happen around a mesh's local origin. If you had a cube going from -1 to 1, its center would be halfway along each dimensions and everything would work perfectly. However, if you had a cube going from 0 to 1, it would rotate along its bottom corner. The way to deal with this is to combine transforms – first, apply a transform to reposition the cube, then apply a rotation transform.

For example, in the case of the one-meter cube above, you would have:
```
// Transforms are applied last-to-first
<Mesh style={transform: {[
  {rotateY: delta}, // Rotate along the y axis some amount
  {translate: [-0.5, -0.5, -0.5]}, // move the center of the cube from (0.5, 0.5, 0.5) to (0, 0, 0)
]}}>
```

If you still want to keep the cube in the same place, you can add a third transform to move it back after the rotation, but I personally find it useful to keep my Meshes centered, and use parent views to reposition them.

Hope this helps!
