### ISSUE TITLE
WebSocket support binarytype arraybuffer

### ISSUE THREAD

**Issue by kyle-ssg** [facebook/react-vr#78]
### Description

Hey, I'm integrating my current project https://github.com/SolidStateGroup/rio in react-vr, I've got it working but have to temporally send JSON strings via websockets rather than an arraybuffer. The message datatype is actually a buffer however it is always empty.

### Reproduction

Send an arraybuffer to a react-vr client

### Solution

Support arraybuffers

* react-vr package version: 0.1.7
* react-vr-web package version: 0.1.7
* Operating System: Any
* Graphics Card: Any
* Browser: Chrome / Nightly
* VR Device: Any

**Comment by andrewimm** [comment]
Resolved in 45a37b681e5c5e1c8abb91421860d863c9315922, will get published in the 1.1.0 release

**Comment by kyle-ssg** [comment]
Thank you very much!

**Comment by andrewimm** [comment]
1.1.0 is available on npm now
