### ISSUE TITLE
Is Oculus Rift supported?

### ISSUE THREAD

**Issue by FezVrasta** [facebook/react-vr#79]
I'd like to start a project using React VR but I don't know what device I can buy.

Is Oculus Rift supported? I see you mention that Carmel VR is supported on Samsung Gear VR, but you don't mention anything about Oculus...

What should I buy to getting started?

**Comment by andrewimm** [comment]
This is covered in the README at the front of the repo:

https://github.com/facebook/react-vr#will-my-web-browser-support-my-vr-headset

If you want to use Rift today, you will be limited to using an "experimental" fork of Chromium or Firefox until Google and Mozilla begin shipping these features in stable versions. Support is not limited by devices, so much as it is limited by browsers supporting these APIs. I would estimate that Chrome will not support WebVR on stable desktop versions until at least May or June 2017.

**Comment by FezVrasta** [comment]
Thank you, I didn't realized that Oculus simply runs Windows apps, sorry for the silly question!

**Comment by FezVrasta** [comment]
@andrewimm sorry if I bother you again.

What about Google Daydream? Can I use Carmel VR on it or the built-in Chrome browser is okay for it?

Sorry for the silly questions but I have zero experience and I can't find a lot of info about React VR 😞

**Comment by andrewimm** [comment]
When Chrome for Android supports WebVR, you will be able to use React VR with Chrome and Daydream. As of now, their implementation is broken and unstable.

By developing on an open standard, we don't tie ourselves to any single piece of hardware. Platforms can support React VR by just supporting the open WebVR APIs.

Apologies if you can't find a lot of information now. React VR is currently a pre-release. When we are ready to release the project fully to the public, we will have much more information on these topics.

**Comment by FezVrasta** [comment]
Yes I totally understand, thank you for the info!
