### ISSUE TITLE
<CylindricalLayer> renders all black in headset

### ISSUE THREAD

**Issue by spikebrehm** [facebook/react-vr#82]
### Description

I'm using the undocumented `<CylindricalLayer>` component.  Viewing in Chrome, it renders as one would expect, but when "View in VR" is enabled, the layer renders completely black.

#### Expected behavior

`<CylindricalLayer>` properly renders in "View in VR" mode.

#### Actual behavior

`<CylindricalLayer>` renders all black "View in VR" mode.

##### "View in VR" == false

![reactvr-cylindricallayer-vr-false](https://cloud.githubusercontent.com/assets/133937/24372865/4598d9e0-12e4-11e7-8525-c637fdbcf4c8.PNG)

##### "View in VR" == true
![reactvr-cylindricallayer-vr-true](https://cloud.githubusercontent.com/assets/133937/24372870/47573b32-12e4-11e7-9562-31942e41b521.PNG)

#### Logs

--

### Reproduction

```js
const WIDTH = 1200;
const HEIGHT = 720;
const DENSITY = 6080;

class CylinderScene extends Component {
  render() {
    return (
      <View>
        <Pano source={asset('beach.jpg')} />
        <CylindricalLayer
          layer={{
            height: HEIGHT,
            width: WIDTH,
            density: DENSITY,
          }}
        >
          <View
            style={{
              backgroundColor: 'rgba(255, 0, 0, 0.4)',
              width: WIDTH,
              height: HEIGHT,
              flex: 1,
              alignItems: 'center',
            }}
          >
            <Image
              source={{ uri: 'https://pbs.twimg.com/profile_images/1101644270/600full-christopher-walken.jpg' }}
              style={{
                width: 400,
                height: 400,
              }}
            />
            <Text style={{ fontSize: 24 }}>
              Walken
            </Text>
          </View>
        </CylindricalLayer>
      </View>
    );
  }
}
```

### Solution

?

### Additional Information

```
├── react-vr@0.1.6
├── react-vr-web@0.1.6
```
* Operating System: Windows
* Graphics Card: ?
* Browser: Chromium webvr build
* VR Device: Oculus Rift

**Comment by mikearmstrong001** [comment]
resolved and fix will follow in next release
