### ISSUE TITLE
Typo in Documentation wrong axis in command description

### ISSUE THREAD

**Issue by codedre** [facebook/react-vr#90]
### Description

On the 3D Coordinates and Transforms page. The description for the rotateZ command says `This command accepts a single value which rotates around the X axis`. Should it be Z axis?

#### Expected behavior

<img width="707" alt="screen shot 2017-04-01 at 9 45 07 pm" src="https://cloud.githubusercontent.com/assets/10161117/24583786/9427c2bc-1724-11e7-8c5a-a85cb8ecebcd.png">

#### Actual behavior

<img width="714" alt="screen shot 2017-04-01 at 9 37 56 pm" src="https://cloud.githubusercontent.com/assets/10161117/24583785/855070d6-1724-11e7-9b96-40eeb04d7f21.png">

### Additional Information

[See here](https://facebook.github.io/react-vr/docs/3dcoordinates-and-transforms.html#transform-properties)

**Comment by mikearmstrong001** [comment]
Thanks for reporting, you are absolutely correct!
I've made the change
