### ISSUE TITLE
Determining if "View in VR" mode is activated or not

### ISSUE THREAD

**Issue by erikriverson** [facebook/react-vr#93]
--- Please use this template, and delete everything above this line before submitting your issue ---

### Description

Is there a method in the React VR API to obtain whether or not "View in VR" mode is currently activated or not? Or perhaps there are events that fire when this mode is entered or exited?

**Comment by mikearmstrong001** [comment]
Certainly can, support will be both events and status check

**Comment by andrewimm** [comment]
@mikearmstrong001 added this before we hit 1.0.0. `VrHeadModel` has method called `getVRStatus()` which returns a boolean tracking whether you're currently in VR.
