### ISSUE TITLE
[Feature Request] Pause Audio

### ISSUE THREAD

**Issue by dukuo** [facebook/react-vr#95]
### Description

[Feature Request] Pause `<Sound>`

#### Expected behavior
Pause `<Sound>`

#### Actual behavior
`<Sound> `stops due to playStatus has only "play" or "stop" values

### Solution
Basically involves storing the elapsed time that the sound has been playing and then offsetting when we create the buffer again. 

in **VRAudioBufferSource.js:** 
initialize `this.startedAt = 0;` ,  `this.pausedAt = 0;` and `this.isPlaying = false;`

then:

```
play: function() {
    if(this._buffer){
      const ctx = this._vrAudioContext.getWebAudioContext();
      const offset = this.pausedAt;

      // Every time play a buffered audio, a new buffer source node need to be created
      this._sourceNode = ctx.createBufferSource();
      this._sourceNode.connect(ctx.destination);
      this._sourceNode.buffer = this._buffer;
      this._sourceNode.onended = this._onMediaEnded.bind(this);
      this._sourceNode.start(0, offset);

      this.startedAt = ctx.currentTime - offset;
      this.pausedAt = 0;
      this.isPlaying = true;
    }
  },
  isSoundPlaying: function(){
    return this.isPlaying;
  },

  pause: function() {
    const ctx = this._vrAudioContext.getWebAudioContext();
    var elapsed = ctx.currentTime - this.startedAt;
    this.stop();
    this.pausedAt = elapsed;
  },

  stop: function() {
    if (this._sourceNode) {
      this._sourceNode.disconnect();
      this._sourceNode.stop(0);
      this._sourceNode = undefined;
    }
    this.pausedAt = 0;
    this.startedAt = 0;
    this.isPlaying = false;
  },

```
in **VRAudioComponent.js**: 
```
  pause: function(){
    if (this._source){
      this._source.pause();
    }
  },
  isPlaying: function() {
    if(this._source){
      return this._source.isSoundPlaying();
    } else {
      return false;
    }
  }
```

I have a working example here https://github.com/dukuo/custom-ovr-audio with the pause feature and such. Any particular reason you are not using promises?

**Comment by dukuo** [comment]
Is this feature plemented yet?

**Comment by larrylin28** [comment]
https://github.com/facebook/react-vr/commit/9a73f598dfd2d4cdd80f6eba5652ba042d2b8f80

**Comment by larrylin28** [comment]
Thanks, this feature is implemented now.

Commit 9a73f598dfd2d4cdd80f6eba5652ba042d2b8f80 closes #95

**Comment by agsirex** [comment]
Delete please lunedì, 24 aprile 2017, 03:49PM +02:00 da Yidong Lin  notifications@github.com :

**Comment by dukuo** [comment]
Thanks @larrylin28 !
