### ISSUE TITLE
Unable to use jsonfile library

### ISSUE THREAD

**Issue by infoxiao** [facebook/react-vr#96]
### Description
Bug

I want to use the library [jsonfile](https://www.npmjs.com/package/jsonfile) to export the data stored in AsyncStorage to a `.json` file so I can analyze offline.

#### Expected behavior

var jsonfile = require('jsonfile')

#### Actual behavior
Unable to resolve module required in ../node_modules/jsonfile/index.js

#### Logs

Unable to resolve module `fs` from `/Users/XXX/Desktop/Data/ReadData/node_modules/jsonfile/index.js`: Module does not exist in the module map or in these directories:
  /Users/XXX/Desktop/Data/ReadData/node_modules

I checked. There is a `fs`folder in the node_modules folder.

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start --reset-cache`.

I tried all these steps and still unable to resolve the issue.

Or any alternative ways that I can export data from AsyncStorage will work.

**Comment by andrewimm** [comment]
It looks like this library is designed to be run in Node.js, not a web environment.

There is no `fs` module for web browsers, since you don't have access to the computer's filesystem. If you want to inspect the contents of AsyncStorage, I recommend using Chrome's developer tools: https://developers.google.com/web/tools/chrome-devtools/manage-data/local-storage#indexeddb. We use IndexedDB as the underlying storage layer for the AsyncStorage implementation.

**Comment by infoxiao** [comment]
Thanks, Andrew. I have a follow-up question if you don't mind...

So right now I am able to bundle my static react-vr project and serve the bundled file as static assets using the express framework on Heroku. What I want is to be able to store user input data on my server's database.

I was able to use AsyncStorage to persist the state of my application.

``
async saveState(){
    let user = {
      secretCode: this.state.secretCode,
      condition: this.state.condition,
      selected: this.state.selected,
    };

    AsyncStorage.setItem(this.state.secretCode, JSON.stringify(user), () => {
      AsyncStorage.getItem(this.state.secretCode, (err, result) => {
        console.log(result);
      });
    });
``

But this is storing into the client's local storage, right? How do I post this data to my server's database though?

**Comment by andrewimm** [comment]
Yes, AsyncStorage is local to the device.

If you want to send data to a remote endpoint, you can use the Fetch API: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API

This allows your browser to make requests to remote endpoints, and send data.

**Comment by infoxiao** [comment]
Fixed. Ended up using the ``import request from 'superagent';``
For some reason trying to import ``request`` package won't work. (In case someone encounter the same problem)
