### ISSUE TITLE
Support for animate sprites ?

### ISSUE THREAD

**Issue by TravisWu** [facebook/react-vr#97]
Any way we can animate sprites ? I notice since px aren't being taken by images I can't exactly animate via CSS, I then tried to just render each image in a loop but the render function takes too long and causes the image to flicker instead

**Comment by dukuo** [comment]
Please edit the title to a more simple one, you can explain what you need in the description.

**Comment by mikearmstrong001** [comment]
I hope you don't mind @TravisWu I alter the title and moved it into the content.

I understand what you are trying to do and it will be something we will look at after we are happy with core support

**Comment by TravisWu** [comment]
@mikearmstrong001  not at all! Thank you for the prompt response, wondering if ReactVR supports Gifs too, I can use that to circumvent my current problem as well

**Comment by andrewimm** [comment]
Just landed custom textures. If you can animate a canvas in the runtime, you can attach it to any <Image> or Mesh

**Comment by TravisWu** [comment]
Awesome! Thank you, this is great :)

**Comment by andrewimm** [comment]
Shipped in 1.2.0
