### ISSUE TITLE
[Feature Request] Allow dashes in project folder name via CLI tool

### ISSUE THREAD

**Issue by RadValentin** [facebook/react-vr#99]
### Description

I want to be able to create projects with dashes in their name:

```
react-vr init react-vr-easter-egg
```

If this is a problem for the actual class name in the generated project (JS doesn't support vars/classes with dashes in them) then those should be camel cased, ex: [_.camelCase](https://lodash.com/docs/4.17.4#camelCase).

#### Expected behavior
This should work

```
react-vr init react-vr-easter-egg
```

#### Actual behavior

```
react-vr init react-vr-easter-egg
Invalid project name: react-vr-easter-egg
```
### Additional Information

* react-vr-cli package version: 0.2.2
* Operating System: Windows

**Comment by rafaelfragosom** [comment]
I can do it today. Is that okay?
